# 04. Combined uncertainty analysis

Combine evidence- and answer-stage uncertainty and evaluate whether they identify incorrect representative answers.

In [1]:
from pathlib import Path
import json
import re

import numpy as np
import pandas as pd
import requests
from scipy.stats import spearmanr
from sklearn.metrics import roc_auc_score

## 1. Configuration

In [2]:
def find_project_root():
    cwd = Path.cwd().resolve()
    for path in [cwd] + list(cwd.parents):
        if (path / "outputs").exists():
            return path
    return cwd

PROJECT_ROOT = find_project_root()
OUTPUT_DIR = PROJECT_ROOT / "outputs"
PROCESSED_DIR = OUTPUT_DIR / "processed_data"

SAMPLE_MODE = False
RUN_NAME = "sample" if SAMPLE_MODE else "full"

EVIDENCE_DIR = OUTPUT_DIR / "evidence_selection" / RUN_NAME
ANSWER_DIR = OUTPUT_DIR / "answer_generation" / RUN_NAME
ANALYSIS_DIR = OUTPUT_DIR / "combined_analysis" / RUN_NAME
ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

JUDGE_BACKEND = "ollama" if SAMPLE_MODE else "vllm"

OLLAMA_JUDGE_MODEL = "gemma3:12b"
VLLM_JUDGE_MODEL = "meta-llama/Llama-3.3-70B-Instruct"

JUDGE_MODEL = (
    OLLAMA_JUDGE_MODEL
    if JUDGE_BACKEND == "ollama"
    else VLLM_JUDGE_MODEL
)

VLLM_BASE_URL = "http://localhost:8000/v1"

JUDGE_TEMPERATURE = 0.0
JUDGE_NUM_CTX = 8192

JUDGE_PATH = ANALYSIS_DIR / "judge_results.jsonl"
CASE_PATH = ANALYSIS_DIR / "case_analysis.csv"
CORRELATION_PATH = ANALYSIS_DIR / "correlations.csv"
PROFILE_PATH = ANALYSIS_DIR / "joint_profile_summary.csv"
PREDICTION_PATH = ANALYSIS_DIR / "prediction_metrics.csv"
RISK_PATH = ANALYSIS_DIR / "risk_coverage.csv"
SELECTIVE_PATH = ANALYSIS_DIR / "selective_review.csv"
HELDOUT_DIR = OUTPUT_DIR / "archehr_heldout"
HELDOUT_PATH = HELDOUT_DIR / "case_analysis.csv"


RUN_BOOTSTRAP = not SAMPLE_MODE
N_BOOTSTRAP = 5000
BOOTSTRAP_SEED = 42
BOOTSTRAP_ALPHA = 0.05

BOOTSTRAP_METRICS_PATH = ANALYSIS_DIR / "bootstrap_metrics.csv"
BOOTSTRAP_COMPARISONS_PATH = (
    ANALYSIS_DIR / "bootstrap_comparisons.csv"
)

## 2. Shared functions

In [3]:
def load_jsonl(path):
    path = Path(path)
    if not path.exists():
        return []
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]

def append_jsonl(record, path):
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

def format_references(reference_answers):
    return "\n".join(
        f"Reference {i}: {answer}"
        for i, answer in enumerate(reference_answers, 1)
    )

def build_judge_prompt(question, reference_answers, answer):
    return f'''
Evaluate the correctness of the generated biomedical answer.

Question:
{question}

Expert reference answer(s):
{format_references(reference_answers)}

Generated answer:
{answer}

Mark the generated answer as correct only if it is substantively correct
and sufficiently complete to answer the question.

Do not penalise paraphrasing or concise wording.
For a multi-part question, omitting a major requested part is incorrect.
A major contradiction or unsupported claim is incorrect.
The generated answer does not need to match every reference exactly.

Return only JSON:
{{"correct": true, "reason": "brief reason"}}
'''.strip()

def call_ollama(prompt, temperature=0.0):
    response = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": JUDGE_MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": temperature,
                "top_p": 0.9,
                "num_predict": 128,
                "num_ctx": JUDGE_NUM_CTX,
            },
        },
        timeout=600,
    )
    response.raise_for_status()

    return response.json()["response"].strip()


def call_vllm(prompt, temperature=0.0):
    response = requests.post(
        f"{VLLM_BASE_URL}/chat/completions",
        json={
            "model": JUDGE_MODEL,
            "messages": [
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            "temperature": temperature,
            "top_p": 0.9,
            "max_completion_tokens": 128,
            "stream": False,
        },
        timeout=600,
    )
    response.raise_for_status()

    return (
        response.json()["choices"][0]["message"]["content"]
        .strip()
    )


def call_judge_model(prompt, temperature=0.0):
    if JUDGE_BACKEND == "ollama":
        return call_ollama(
            prompt,
            temperature=temperature,
        )

    if JUDGE_BACKEND == "vllm":
        return call_vllm(
            prompt,
            temperature=temperature,
        )

    raise ValueError(
        f"Unknown judge backend: {JUDGE_BACKEND}"
    )


def check_judge_server():
    if JUDGE_BACKEND == "ollama":
        url = "http://localhost:11434/"
    else:
        url = f"{VLLM_BASE_URL}/models"

    response = requests.get(
        url,
        timeout=10,
    )
    response.raise_for_status()


def parse_judgement(text):
    text = text.replace("```json", "").replace("```", "").strip()

    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*?\}", text, flags=re.DOTALL)
        if match is None:
            return None
        try:
            data = json.loads(match.group(0))
        except json.JSONDecodeError:
            return None

    correct = data.get("correct")
    if isinstance(correct, bool):
        value = correct
    elif isinstance(correct, int) and correct in (0, 1):
        value = bool(correct)
    else:
        return None

    return {
        "correct": value,
        "reason": str(data.get("reason", "")).strip(),
    }

def judge_answer(question, reference_answers, answer):
    prompt = build_judge_prompt(
        question,
        reference_answers,
        answer,
    )

    for _ in range(2):
        result = parse_judgement(
            call_judge_model(
                prompt,
                temperature=JUDGE_TEMPERATURE,
            )
        )
        if result is not None:
            return result

    raise ValueError("Could not parse judge response.")

def representative_answer(group):
    group = group.sort_values("run_id").copy()
    group["cluster_label"] = group["cluster_label"].astype(int)

    counts = group["cluster_label"].value_counts()
    largest = counts.max()
    tied_labels = set(counts[counts == largest].index.tolist())

    # If clusters tie, use the cluster containing the earliest run.
    dominant_label = int(
        group[group["cluster_label"].isin(tied_labels)]
        .iloc[0]["cluster_label"]
    )

    dominant = group[
        group["cluster_label"] == dominant_label
    ].sort_values("run_id")

    row = dominant.iloc[0]

    return {
        "representative_answer": row["answer"],
        "representative_run_id": int(row["run_id"]),
        "representative_cluster_size": len(dominant),
    }

def safe_spearman(x, y):
    data = pd.DataFrame({"x": x, "y": y}).dropna()

    if (
        len(data) < 3
        or data["x"].nunique() < 2
        or data["y"].nunique() < 2
    ):
        return np.nan, np.nan, len(data)

    rho, p_value = spearmanr(data["x"], data["y"])
    return float(rho), float(p_value), len(data)

def safe_auroc(y_true, scores):
    data = pd.DataFrame({
        "y": y_true,
        "score": scores,
    }).dropna()

    if len(data) < 2 or data["y"].nunique() < 2:
        return np.nan

    return float(
        roc_auc_score(
            data["y"].astype(int),
            data["score"],
        )
    )

# Calculate risk-coverage curve with tie handling
def compute_risk_coverage(group, signal):

    data = (
        group[[signal, "answer_error"]]
        .dropna()
        .copy()
    )

    # Group cases with the same uncertainty score
    tie_groups = (
        data.groupby(signal, sort=True)["answer_error"]
        .agg(["size", "sum"])
        .reset_index()
    )

    rows = []

    retained_before = 0
    errors_before = 0.0
    n = len(data)

    for row in tie_groups.itertuples(index=False):

        tie_n = row.size
        tie_errors = row.sum
        tie_error_rate = tie_errors / tie_n

        # Use expected error within each tied group
        for r in range(1, tie_n + 1):

            n_retained = retained_before + r

            expected_errors = (
                errors_before
                + r * tie_error_rate
            )

            error_rate = (
                expected_errors / n_retained
            )

            rows.append({
                "coverage": n_retained / n,
                "n_retained": n_retained,
                "retained_error_rate": error_rate,
                "retained_correctness": 1.0 - error_rate,
            })

        retained_before += tie_n
        errors_before += tie_errors

    return pd.DataFrame(rows)


# Report risk at selected coverage levels
def selective_review(
    group,
    signal,
    targets=(1.0, 0.9, 0.8, 0.7, 0.6),
):

    curve = compute_risk_coverage(
        group,
        signal,
    )

    rows = []
    n = len(curve)

    for target in targets:

        k = max(
            1,
            int(np.ceil(target * n)),
        )

        row = curve.iloc[k - 1]

        rows.append({
            "target_coverage": target,
            "coverage": row["coverage"],
            "n_retained": int(row["n_retained"]),
            "retained_error_rate": row["retained_error_rate"],
            "retained_correctness": row["retained_correctness"],
        })

    return pd.DataFrame(rows)

## 3. Load previous outputs

In [4]:
evidence_summary = pd.read_csv(
    EVIDENCE_DIR / "evidence_summary.csv"
)

answer_summary = pd.read_csv(
    ANSWER_DIR / "answer_summary.csv"
)

answer_runs = pd.read_csv(
    ANSWER_DIR / "answer_runs_with_clusters.csv"
)

analysis = evidence_summary.merge(
    answer_summary,
    on=["analysis_set", "case_id"],
    how="inner",
    validate="one_to_one",
)

current_keys = set(
    zip(
        analysis["analysis_set"],
        analysis["case_id"],
    )
)

answer_runs = answer_runs[
    [
        (analysis_set, case_id) in current_keys
        for analysis_set, case_id in zip(
            answer_runs["analysis_set"],
            answer_runs["case_id"],
        )
    ]
].copy()

case_files = {
    "bioasq_train": PROCESSED_DIR / "bioasq_train_cases.jsonl",
    "bioasq_test": PROCESSED_DIR / "bioasq_test_cases.jsonl",
    "archehr_train": PROCESSED_DIR / "archehr_train_cases.jsonl",
    "archehr_test": PROCESSED_DIR / "archehr_test_cases.jsonl",
}

active_sets = set(analysis["analysis_set"])

case_by_key = {
    (analysis_set, case["case_id"]): case
    for analysis_set, path in case_files.items()
    if analysis_set in active_sets
    for case in load_jsonl(path)
}

print("Cases loaded:", len(analysis))
print(analysis["analysis_set"].value_counts())

Cases loaded: 993
analysis_set
bioasq_train     973
archehr_train     20
Name: count, dtype: int64

## 4. Select representative answers

The representative answer is taken from the largest semantic answer cluster from Notebook 03.

In [5]:
representative_rows = []

for (analysis_set, case_id), group in answer_runs.groupby(
    ["analysis_set", "case_id"],
    sort=False,
):
    row = representative_answer(group)
    row.update({
        "analysis_set": analysis_set,
        "case_id": case_id,
    })
    representative_rows.append(row)

representative_df = pd.DataFrame(representative_rows)

analysis = analysis.merge(
    representative_df,
    on=["analysis_set", "case_id"],
    how="left",
    validate="one_to_one",
)

if analysis["representative_answer"].isna().any():
    missing = analysis.loc[
        analysis["representative_answer"].isna(),
        ["analysis_set", "case_id"],
    ]
    raise ValueError(
        f"Missing representative answers:\n{missing}"
    )

display(
    analysis[
        [
            "analysis_set",
            "case_id",
            "evidence_uncertainty",
            "answer_uncertainty",
            "answer_pairwise_distance",
            "representative_cluster_size",
        ]
    ]
)

,analysis_set,case_id,evidence_uncertainty,answer_uncertainty,answer_pairwise_distance,representative_cluster_size
0,bioasq_train,bioasq13b_55031181e9bde69634000014,0.222176,-0.000000,0.046087,10
1,bioasq_train,bioasq13b_532f062ad6d3ac6a34000027,0.374005,0.141182,0.055142,9
2,bioasq_train,bioasq13b_54f49995d0d681a040000002,0.311111,-0.000000,0.002728,10
3,bioasq_train,bioasq13b_535d78137d100faa09000005,0.273505,-0.000000,0.053254,10
4,bioasq_train,bioasq13b_52d946c798d023950500000a,0.323552,-0.000000,0.031167,10
...,...,...,...,...,...,...
988,archehr_train,archehr_16,0.000000,-0.000000,0.007544,10
989,archehr_train,archehr_17,0.040000,0.447173,0.147417,5
990,archehr_train,archehr_18,0.405185,0.141182,0.060100,9
991,archehr_train,archehr_19,0.000000,0.277528,0.083709,8
992,archehr_train,archehr_20,0.000000,0.141182,0.055931,9

## 5. Judge representative-answer correctness

Correctness is evaluated automatically against the expert reference answer(s). This is an evaluation proxy rather than clinical ground truth.

In [6]:
existing_judges = load_jsonl(JUDGE_PATH)

judge_lookup = {
    (
        row["analysis_set"],
        row["case_id"],
        row["representative_answer"],
    ): row
    for row in existing_judges
}

# Check whether any judge results are missing
missing_judges = [
    row
    for row in analysis.itertuples()
    if (
        row.analysis_set,
        row.case_id,
        row.representative_answer,
    ) not in judge_lookup
]

print("Loaded judge results:", len(judge_lookup))
print("Missing judge results:", len(missing_judges))

# Only run the judge model if results are missing
if missing_judges:

    try:
        check_judge_server()
    except Exception as exc:
        raise RuntimeError(
            f"Start {JUDGE_BACKEND} before running answer evaluation."
        ) from exc

    for row in missing_judges:

        case = case_by_key[
            (row.analysis_set, row.case_id)
        ]

        result = judge_answer(
            case["question"],
            case["reference_answers"],
            row.representative_answer,
        )

        record = {
            "analysis_set": row.analysis_set,
            "case_id": row.case_id,
            "representative_answer": row.representative_answer,
            "correct": bool(result["correct"]),
            "reason": result["reason"],
        }

        append_jsonl(record, JUDGE_PATH)

        key = (
            row.analysis_set,
            row.case_id,
            row.representative_answer,
        )

        judge_lookup[key] = record

        print(
            row.analysis_set,
            row.case_id,
            result["correct"],
        )


analysis["judge_correct"] = [
    judge_lookup[
        (
            row.analysis_set,
            row.case_id,
            row.representative_answer,
        )
    ]["correct"]
    for row in analysis.itertuples()
]

analysis["judge_reason"] = [
    judge_lookup[
        (
            row.analysis_set,
            row.case_id,
            row.representative_answer,
        )
    ]["reason"]
    for row in analysis.itertuples()
]

analysis["judge_correct"] = (
    analysis["judge_correct"].astype(int)
)

analysis["answer_error"] = (
    1 - analysis["judge_correct"]
)

Loaded judge results: 993
Missing judge results: 0

## 6. Combined analysis

In [7]:
# Both primary uncertainty measures are already normalised to 0-1.
analysis["combined_uncertainty"] = (
    analysis["evidence_uncertainty"]
    + analysis["answer_uncertainty"]
) / 2.0


# Joint behavioural profiles
# EU = 0: stable evidence selection
# EU > 0: unstable evidence selection
# AU = 0: stable answer generation
# AU > 0: variable answer generation

analysis["evidence_profile"] = np.where(
    analysis["evidence_uncertainty"] == 0,
    "Stable",
    "Unstable",
)

analysis["answer_profile"] = np.where(
    analysis["answer_uncertainty"] == 0,
    "Stable",
    "Variable",
)

analysis["joint_profile"] = (
    analysis["evidence_profile"]
    + "–"
    + analysis["answer_profile"]
)


# Save case-level analysis with profile labels
analysis.to_csv(
    CASE_PATH,
    index=False,
)


# Correlations
correlation_rows = []

correlation_pairs = [
    (
        "evidence_vs_answer_uncertainty",
        "evidence_uncertainty",
        "answer_uncertainty",
    ),
    (
        "evidence_uncertainty_vs_answer_error",
        "evidence_uncertainty",
        "answer_error",
    ),
    (
        "answer_uncertainty_vs_answer_error",
        "answer_uncertainty",
        "answer_error",
    ),
    (
        "combined_uncertainty_vs_answer_error",
        "combined_uncertainty",
        "answer_error",
    ),
    (
        "pairwise_distance_vs_answer_error",
        "answer_pairwise_distance",
        "answer_error",
    ),
    (
        "evidence_uncertainty_vs_evidence_recall",
        "evidence_uncertainty",
        "evidence_recall",
    ),
    (
        "evidence_uncertainty_vs_evidence_f1",
        "evidence_uncertainty",
        "evidence_f1",
    ),
]

for analysis_set, group in analysis.groupby(
    "analysis_set",
    sort=False,
):
    for relationship, x_col, y_col in correlation_pairs:
        rho, p_value, n = safe_spearman(
            group[x_col],
            group[y_col],
        )

        correlation_rows.append({
            "analysis_set": analysis_set,
            "relationship": relationship,
            "n": n,
            "spearman_rho": rho,
            "p_value": p_value,
        })

correlations = pd.DataFrame(correlation_rows)

correlations.to_csv(
    CORRELATION_PATH,
    index=False,
)


# Reliability prediction
primary_signals = [
    "evidence_uncertainty",
    "answer_uncertainty",
    "combined_uncertainty",
]

companion_signals = [
    "answer_pairwise_distance",
]

prediction_rows = []
risk_rows = []
selective_rows = []

for analysis_set, group in analysis.groupby(
    "analysis_set",
    sort=False,
):
    for signal in primary_signals + companion_signals:

        curve = compute_risk_coverage(
            group,
            signal,
        )

        for row in curve.itertuples():
            risk_rows.append({
                "analysis_set": analysis_set,
                "signal": signal,
                "coverage": row.coverage,
                "n_retained": row.n_retained,
                "retained_error_rate": row.retained_error_rate,
                "retained_correctness": row.retained_correctness,
            })

        prediction_rows.append({
            "analysis_set": analysis_set,
            "signal": signal,
            "signal_role": (
                "primary"
                if signal in primary_signals
                else "companion"
            ),
            "n_cases": len(group),
            "n_incorrect": int(
                group["answer_error"].sum()
            ),
            "incorrect_rate": (
                group["answer_error"].mean()
            ),
            "auroc": safe_auroc(
                group["answer_error"],
                group[signal],
            ),
            # Lower AURC is better.
            "aurc": (
                curve["retained_error_rate"].mean()
            ),
        })

    for signal in primary_signals:
        table = selective_review(
            group,
            signal,
        )

        for row in table.itertuples():
            selective_rows.append({
                "analysis_set": analysis_set,
                "signal": signal,
                "target_coverage": row.target_coverage,
                "coverage": row.coverage,
                "n_retained": row.n_retained,
                "retained_error_rate": row.retained_error_rate,
                "retained_correctness": row.retained_correctness,
            })


prediction_metrics = pd.DataFrame(
    prediction_rows
)

risk_coverage = pd.DataFrame(
    risk_rows
)

selective_review_table = pd.DataFrame(
    selective_rows
)

prediction_metrics.to_csv(
    PREDICTION_PATH,
    index=False,
)

risk_coverage.to_csv(
    RISK_PATH,
    index=False,
)

selective_review_table.to_csv(
    SELECTIVE_PATH,
    index=False,
)

# Joint profile summary
profile_order = [
    "Stable–Stable",
    "Stable–Variable",
    "Unstable–Stable",
    "Unstable–Variable",
]

analysis["joint_profile"] = pd.Categorical(
    analysis["joint_profile"],
    categories=profile_order,
    ordered=True,
)

profile_summary = (
    analysis
    .groupby(
        ["analysis_set", "joint_profile"],
        observed=False,
    )
    .agg(
        n=("case_id", "size"),
        correct_n=("judge_correct", "sum"),
        incorrect_n=("answer_error", "sum"),
        error_rate=("answer_error", "mean"),
        median_eu=("evidence_uncertainty", "median"),
        median_au=("answer_uncertainty", "median"),
    )
    .reset_index()
)

profile_summary["profile_percent"] = (
    profile_summary["n"]
    / profile_summary.groupby(
        "analysis_set"
    )["n"].transform("sum")
    * 100
)

profile_summary.to_csv(
    PROFILE_PATH,
    index=False,
)


print("Saved:", ANALYSIS_DIR)

display(
    analysis.groupby("analysis_set")[
        [
            "evidence_uncertainty",
            "answer_uncertainty",
            "answer_pairwise_distance",
            "judge_correct",
        ]
    ].mean()
)

display(
    prediction_metrics[
        prediction_metrics["signal_role"]
        == "primary"
    ]
)

display(
    correlations[
        correlations["relationship"]
        == "evidence_vs_answer_uncertainty"
    ]
)

display(
    selective_review_table[
        selective_review_table["signal"]
        == "combined_uncertainty"
    ]
)

display(profile_summary)

Saved: /Users/sangbin/Desktop/Dissertation/Msc_Dissertation/outputs/combined_analysis/full

,evidence_uncertainty,answer_uncertainty,answer_pairwise_distance,judge_correct
analysis_set,,,,
archehr_train,0.065459,0.128494,0.051251,0.450000
bioasq_train,0.144070,0.018976,0.023966,0.873587

,analysis_set,signal,signal_role,n_cases,n_incorrect,incorrect_rate,auroc,aurc
0,bioasq_train,evidence_uncertainty,primary,973,123,0.126413,0.586112,0.101345
1,bioasq_train,answer_uncertainty,primary,973,123,0.126413,0.515275,0.123042
2,bioasq_train,combined_uncertainty,primary,973,123,0.126413,0.586992,0.100640
4,archehr_train,evidence_uncertainty,primary,20,11,0.550000,0.459596,0.574625
5,archehr_train,answer_uncertainty,primary,20,11,0.550000,0.419192,0.605768
6,archehr_train,combined_uncertainty,primary,20,11,0.550000,0.398990,0.611254

    analysis_set                    relationship    n  spearman_rho   p_value
0   bioasq_train  evidence_vs_answer_uncertainty  973      0.117209  0.000248
7  archehr_train  evidence_vs_answer_uncertainty   20      0.201570  0.394101

,analysis_set,signal,target_coverage,coverage,n_retained,retained_error_rate,retained_correctness
10,bioasq_train,combined_uncertainty,1.0,1.000000,973,0.126413,0.873587
11,bioasq_train,combined_uncertainty,0.9,0.900308,876,0.118721,0.881279
12,bioasq_train,combined_uncertainty,0.8,0.800617,779,0.114249,0.885751
13,bioasq_train,combined_uncertainty,0.7,0.700925,682,0.102639,0.897361
14,bioasq_train,combined_uncertainty,0.6,0.600206,584,0.102740,0.897260
25,archehr_train,combined_uncertainty,1.0,1.000000,20,0.550000,0.450000
26,archehr_train,combined_uncertainty,0.9,0.900000,18,0.555556,0.444444
27,archehr_train,combined_uncertainty,0.8,0.800000,16,0.562500,0.437500
28,archehr_train,combined_uncertainty,0.7,0.700000,14,0.571429,0.428571
29,archehr_train,combined_uncertainty,0.6,0.600000,12,0.666667,0.333333

,analysis_set,joint_profile,n,correct_n,incorrect_n,error_rate,median_eu,median_au,profile_percent
0,archehr_train,Stable–Stable,8,3,5,0.625000,0.000000,-0.000000,40.000000
1,archehr_train,Stable–Variable,4,2,2,0.500000,0.000000,0.247425,20.000000
2,archehr_train,Unstable–Stable,3,1,2,0.666667,0.133333,-0.000000,15.000000
3,archehr_train,Unstable–Variable,5,3,2,0.400000,0.093407,0.217322,25.000000
4,bioasq_train,Stable–Stable,357,325,32,0.089636,0.000000,-0.000000,36.690647
5,bioasq_train,Stable–Variable,12,10,2,0.166667,0.000000,0.141182,1.233299
6,bioasq_train,Unstable–Stable,537,459,78,0.145251,0.209562,-0.000000,55.190134
7,bioasq_train,Unstable–Variable,67,56,11,0.164179,0.198122,0.217322,6.885920

## 7. Bootstrap 95% confidence intervals

Bootstrap 95% confidence intervals were used for the final RQ3 and RQ4 metrics.

In [8]:
# Calculate percentile-based 95% CI
def percentile_ci(values, alpha=0.05):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]

    if len(values) == 0:
        return np.nan, np.nan

    return (
        np.quantile(values, alpha / 2),
        np.quantile(values, 1 - alpha / 2),
    )

# Calculate AURC from the risk-coverage curve
def aurc_score(df, signal):
    curve = compute_risk_coverage(df, signal)
    return curve["retained_error_rate"].mean()

# Resample correct and incorrect cases separately
def stratified_sample(df, rng):
    sampled = []

    for label in df["answer_error"].unique():
        idx = df.index[df["answer_error"] == label]
        sampled.extend(
            rng.choice(idx, size=len(idx), replace=True)
        )

    return df.loc[sampled].reset_index(drop=True)

# Bootstrap 95% CI for RQ3 Spearman correlation
def bootstrap_spearman(
    df,
    n_bootstrap=N_BOOTSTRAP,
    seed=BOOTSTRAP_SEED,
):     

    rng = np.random.default_rng(seed)

    rho, _, _ = safe_spearman(
        df["evidence_uncertainty"],
        df["answer_uncertainty"],
    )

    boot_rho = []

    for _ in range(n_bootstrap):
        sample = df.sample(
            n=len(df),
            replace=True,
            random_state=int(rng.integers(0, 1_000_000)),
        )

        r, _, _ = safe_spearman(
            sample["evidence_uncertainty"],
            sample["answer_uncertainty"],
        )

        if np.isfinite(r):
            boot_rho.append(r)

    lower, upper = percentile_ci(
        boot_rho,
        BOOTSTRAP_ALPHA,
    )

    return rho, lower, upper

# Paired stratified bootstrap for AUROC and AURC
def bootstrap_rq4(
    df,
    signals,
    n_bootstrap=N_BOOTSTRAP,
    seed=BOOTSTRAP_SEED,
):     

    point = {}

    for signal in signals:
        point[signal] = {
            "auroc": safe_auroc(
                df["answer_error"],
                df[signal],
            ),
            "aurc": aurc_score(df, signal),
        }

    boot = {
        signal: {"auroc": [], "aurc": []}
        for signal in signals
    }

    comparisons = {
        "combined_minus_evidence": {
            "auroc": [],
            "aurc": [],
        },
        "combined_minus_answer": {
            "auroc": [],
            "aurc": [],
        },
    }

    rng = np.random.default_rng(seed)

    for _ in range(n_bootstrap):
        sample = stratified_sample(df, rng)

        results = {}

        for signal in signals:
            auroc = safe_auroc(
                sample["answer_error"],
                sample[signal],
            )
            aurc = aurc_score(sample, signal)

            results[signal] = {
                "auroc": auroc,
                "aurc": aurc,
            }

            boot[signal]["auroc"].append(auroc)
            boot[signal]["aurc"].append(aurc)

        # Compare combined uncertainty with evidence uncertainty
        comparisons["combined_minus_evidence"]["auroc"].append(
            results["combined_uncertainty"]["auroc"]
            - results["evidence_uncertainty"]["auroc"]
        )

        comparisons["combined_minus_evidence"]["aurc"].append(
            results["combined_uncertainty"]["aurc"]
            - results["evidence_uncertainty"]["aurc"]
        )

        # Compare combined uncertainty with answer uncertainty
        comparisons["combined_minus_answer"]["auroc"].append(
            results["combined_uncertainty"]["auroc"]
            - results["answer_uncertainty"]["auroc"]
        )

        comparisons["combined_minus_answer"]["aurc"].append(
            results["combined_uncertainty"]["aurc"]
            - results["answer_uncertainty"]["aurc"]
        )

    metric_rows = []

    for signal in signals:
        for metric in ["auroc", "aurc"]:
            lower, upper = percentile_ci(
                boot[signal][metric],
                BOOTSTRAP_ALPHA,
            )

            metric_rows.append({
                "signal": signal,
                "metric": metric,
                "point_estimate": point[signal][metric],
                "ci_lower": lower,
                "ci_upper": upper,
            })

    comparison_rows = []

    comparison_pairs = {
        "combined_minus_evidence":
            ("combined_uncertainty", "evidence_uncertainty"),
        "combined_minus_answer":
            ("combined_uncertainty", "answer_uncertainty"),
    }

    for name, (combined, other) in comparison_pairs.items():
        for metric in ["auroc", "aurc"]:
            lower, upper = percentile_ci(
                comparisons[name][metric],
                BOOTSTRAP_ALPHA,
            )

            comparison_rows.append({
                "comparison": name,
                "metric": metric,
                "point_difference":
                    point[combined][metric]
                    - point[other][metric],
                "ci_lower": lower,
                "ci_upper": upper,
            })

    return metric_rows, comparison_rows


if RUN_BOOTSTRAP:

    bootstrap_metrics = []
    bootstrap_comparisons = []

    # Run bootstrap separately for each analysis dataset
    for i, (analysis_set, group) in enumerate(
        analysis.groupby("analysis_set", sort=False)
    ):
        group = group.reset_index(drop=True)
        seed = BOOTSTRAP_SEED + i

        # RQ3: relationship between evidence and answer uncertainty
        rho, rho_lower, rho_upper = bootstrap_spearman(
            group,
            seed=seed,
        )

        bootstrap_metrics.append({
            "analysis_set": analysis_set,
            "signal": "evidence_vs_answer_uncertainty",
            "metric": "spearman_rho",
            "point_estimate": rho,
            "ci_lower": rho_lower,
            "ci_upper": rho_upper,
        })

        # RQ4 requires both correct and incorrect cases
        if group["answer_error"].nunique() >= 2:

            metric_rows, comparison_rows = bootstrap_rq4(
                group,
                primary_signals,
                seed=seed + 1,
            )

            for row in metric_rows:
                row["analysis_set"] = analysis_set
                bootstrap_metrics.append(row)

            for row in comparison_rows:
                row["analysis_set"] = analysis_set
                bootstrap_comparisons.append(row)

    bootstrap_metrics = pd.DataFrame(bootstrap_metrics)
    bootstrap_comparisons = pd.DataFrame(
        bootstrap_comparisons
    )

    # Save bootstrap results
    bootstrap_metrics.to_csv(
        BOOTSTRAP_METRICS_PATH,
        index=False,
    )

    bootstrap_comparisons.to_csv(
        BOOTSTRAP_COMPARISONS_PATH,
        index=False,
    )

    display(bootstrap_metrics)
    display(bootstrap_comparisons)

else:
    print("Bootstrap skipped in SAMPLE_MODE.")

,analysis_set,signal,metric,point_estimate,ci_lower,ci_upper
0,bioasq_train,evidence_vs_answer_uncertainty,spearman_rho,0.117209,0.060470,0.173966
1,bioasq_train,evidence_uncertainty,auroc,0.586112,0.534385,0.637859
2,bioasq_train,evidence_uncertainty,aurc,0.101345,0.085650,0.116984
3,bioasq_train,answer_uncertainty,auroc,0.515275,0.487230,0.546153
4,bioasq_train,answer_uncertainty,aurc,0.123042,0.116018,0.129423
5,bioasq_train,combined_uncertainty,auroc,0.586992,0.535088,0.638085
6,bioasq_train,combined_uncertainty,aurc,0.100640,0.084865,0.116005
7,archehr_train,evidence_vs_answer_uncertainty,spearman_rho,0.201570,-0.222852,0.618000
8,archehr_train,evidence_uncertainty,auroc,0.459596,0.232323,0.686869
9,archehr_train,evidence_uncertainty,aurc,0.574625,0.441104,0.715615
10,archehr_train,answer_uncertainty,auroc,0.419192,0.191919,0.651515
11,archehr_train,answer_uncertainty,aurc,0.605768,0.465052,0.745735
12,archehr_train,combined_uncertainty,auroc,0.398990,0.156566,0.651515
13,archehr_train,combined_uncertainty,aurc,0.611254,0.442875,0.777294

,comparison,metric,point_difference,ci_lower,ci_upper,analysis_set
0,combined_minus_evidence,auroc,0.000880,-0.014333,0.018500,bioasq_train
1,combined_minus_evidence,aurc,-0.000705,-0.005724,0.003125,bioasq_train
2,combined_minus_answer,auroc,0.071717,0.023430,0.120911,bioasq_train
3,combined_minus_answer,aurc,-0.022402,-0.037578,-0.007389,bioasq_train
4,combined_minus_evidence,auroc,-0.060606,-0.282828,0.141414,archehr_train
5,combined_minus_evidence,aurc,0.036629,-0.085746,0.174817,archehr_train
6,combined_minus_answer,auroc,-0.020202,-0.171717,0.116162,archehr_train
7,combined_minus_answer,aurc,0.005486,-0.084288,0.110583,archehr_train

## 8. Reviews

#### 1) Manual Review of Judge Outputs

Manual review to compare a subset of the correctness judgements by LLM with manual assessment.

For ArchEHR-QA development cases, all 20  were included and for BioASQ, 10 cases
judged correct and 10 cases judged incorrect were randomly selected.

In [18]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', 1000)

REVIEW_SEED = 42
REVIEW_PATH = ANALYSIS_DIR / "manual_judge_review.csv"

if REVIEW_PATH.exists():
    print("Manual review file already exists:")
    print(REVIEW_PATH)

else:
    # All 20 ArchEHR development cases
    arch_review = analysis[
        analysis["analysis_set"] == "archehr_train"
    ].copy()

    assert len(arch_review) == 20

    # BioASQ development cases
    bio = analysis[
        analysis["analysis_set"] == "bioasq_train"
    ].copy()

    # 10 judged correct cases
    bio_correct = bio[
        bio["judge_correct"] == 1
    ].sample(
        n=10,
        random_state=REVIEW_SEED,
    )

    # 10 judged incorrect cases
    bio_incorrect = bio[
        bio["judge_correct"] == 0
    ].sample(
        n=10,
        random_state=REVIEW_SEED,
    )

    # Combine review cases
    review = pd.concat(
        [
            arch_review,
            bio_correct,
            bio_incorrect,
        ],
        ignore_index=True,
    )

    # Shuffle review order
    review = review.sample(
        frac=1,
        random_state=REVIEW_SEED,
    ).reset_index(drop=True)

    review["review_id"] = [
        f"R{i:02d}"
        for i in range(1, len(review) + 1)
    ]

    # Add question and reference answer
    questions = []
    references = []

    for row in review.itertuples():

        case = case_by_key[
            (row.analysis_set, row.case_id)
        ]

        questions.append(
            case["question"]
        )

        references.append(
            "\n\n".join(
                case["reference_answers"]
            )
        )

    review["question"] = questions
    review["reference_answers"] = references

    # Keep only information needed for blinded review
    manual_review = review[
        [
            "review_id",
            "analysis_set",
            "case_id",
            "question",
            "reference_answers",
            "representative_answer",
        ]
    ].copy()

    manual_review["manual_label"] = ""

    manual_review.to_csv(
        REVIEW_PATH,
        index=False,
    )

    print("Saved:", REVIEW_PATH)

Manual review file already exists:
/Users/sangbin/Desktop/Dissertation/Msc_Dissertation/outputs/combined_analysis/full/manual_judge_review.csv

In [19]:
# Compare manual review with LLM judge result

manual_review = pd.read_csv(REVIEW_PATH)

manual_review["manual_label"] = (
    manual_review["manual_label"]
    .fillna("")
    .str.strip()
)

# Check manual labels
allowed_labels = {
    "Correct",
    "Incorrect",
    "Unclear",
}

invalid = manual_review[
    ~manual_review["manual_label"].isin(allowed_labels)
]

if len(invalid) > 0:
    display(
        invalid[
            [
                "review_id",
                "manual_label",
            ]
        ]
    )

    raise ValueError(
        "Use only Correct, Incorrect, or Unclear."
    )

# Add LLM judge result
judge_review_results = analysis[
    [
        "analysis_set",
        "case_id",
        "representative_answer",
        "judge_correct",
        "judge_reason",
    ]
].copy()

comparison = manual_review.merge(
    judge_review_results,
    on=[
        "analysis_set",
        "case_id",
        "representative_answer",
    ],
    how="left",
    validate="one_to_one",
)

comparison["judge_label"] = (
    comparison["judge_correct"]
    .astype(int)
    .map({
        1: "Correct",
        0: "Incorrect",
    })
)

# Compare manual and judge labels
comparison["comparison"] = [
    "Manual unclear"
    if manual == "Unclear"
    else "Agree"
    if manual == judge
    else "Disagree"
    for manual, judge in zip(
        comparison["manual_label"],
        comparison["judge_label"],
    )
]

print(
    comparison["comparison"].value_counts()
)

display(
    comparison.groupby(
        [
            "analysis_set",
            "comparison",
        ]
    )
    .size()
    .rename("n")
    .reset_index()
)

# Review disagreements
disagreements = comparison[
    comparison["comparison"] == "Disagree"
].copy()

print(
    "Disagreements:",
    len(disagreements),
)

display(
    disagreements[
        [
            "review_id",
            "analysis_set",
            "case_id",
            "manual_label",
            "judge_label",
            "judge_reason",
        ]
    ]
)

comparison
Agree             25
Disagree          12
Manual unclear     3
Name: count, dtype: int64

    analysis_set      comparison   n
0  archehr_train           Agree  13
1  archehr_train        Disagree   5
2  archehr_train  Manual unclear   2
3   bioasq_train           Agree  12
4   bioasq_train        Disagree   7
5   bioasq_train  Manual unclear   1

Disagreements: 12

   review_id   analysis_set                             case_id manual_label judge_label                                                                                                                                                                                                          judge_reason
1        R02  archehr_train                          archehr_17      Correct   Incorrect                                                                 The generated answer does not address relieving palpitations and anxiety, and instead mentions unrelated medications and administration instructions.
6        R07   bioasq_train  bioasq13b_623648513a8413c6530000ae      Correct   Incorrect  The generated answer inaccurately limits AIS to describing traumatic brain injury (TBI) and does not mention its broader application to all body regions or its role in determining the Injury Severity Score (ISS).
8        R09   bioasq_train  bioasq13b_5a43a933966455904c00000b      Correct   Incorrect                                                                                                                                                                         unsupported claim about oxidation derivatives
10       R11   bioasq_train  bioasq13b_56a3a6c9496b62f23f000008    Incorrect     Correct                                       The generated answer accurately describes TFBSshape as a tool for calculating DNA structural features from nucleotide sequences, which aligns with the expert reference answer.
12       R13  archehr_train                          archehr_14      Correct   Incorrect                                                                 The generated answer does not directly address the question about stomach cancer and introduces unrelated information about bladder cancer treatment.
19       R20   bioasq_train  bioasq13b_606b61f794d57fd879000068      Correct   Incorrect                                                             The generated answer claims that the downstream effects and mechanisms of NPRA are largely unknown, which contradicts the provided reference information.
20       R21  archehr_train                           archehr_6      Correct   Incorrect                                      generated answer contains unsupported claims and contradictions, such as mentioning *Torulopsis glabrata* and treatment with mica, which are not present in the reference answer
25       R26  archehr_train                           archehr_3      Correct   Incorrect                  omitted major parts of the expected course of recovery, such as short-term memory loss, reporting new symptoms, and specific symptoms to report like visual changes, weakness, and speech difficulty
26       R27   bioasq_train  bioasq13b_530cf22aa177c6630c000001      Correct   Incorrect                                                generated answer introduces unsupported claims and details not present in the reference, such as regulating chitin synthase and cooperating with Cyk3 to activate Chs2
27       R28   bioasq_train  bioasq13b_5c6585097c78d69471000003      Correct   Incorrect                                                                                        unsupported claims about regulating cardiac gene expression, promoting nuclear import of 53BP1, and implication in mRNA export
31       R32   bioasq_train  bioasq13b_587e42032420191125000004      Correct   Incorrect                                                             generated answer introduces unsupported claim (FAM63A) and lacks key information about MINDY-1's function and characteristics mentioned in the references
36       R37  archehr_train                           archehr_8      Correct   Incorrect                                                     The generated answer does not address if the poison damage will last and omits discussion on potential long-term cognitive deficits related to the toxin buildup.

In [11]:
# Review disagreement cases

disagreement_review = disagreements.copy()

questions = []
references = []

for row in disagreement_review.itertuples():

    case = case_by_key[
        (row.analysis_set, row.case_id)
    ]

    questions.append(
        case["question"]
    )

    references.append(
        "\n\n".join(
            case["reference_answers"]
        )
    )

disagreement_review["question"] = questions
disagreement_review["reference_answers"] = references

display(
    disagreement_review[
        [
            "review_id",
            "analysis_set",
            "case_id",
            "question",
            "reference_answers",
            "representative_answer",
            "manual_label",
            "judge_label",
            "judge_reason",
        ]
    ]
)

,review_id,analysis_set,case_id,question,reference_answers,representative_answer,manual_label,judge_label,judge_reason
1,R02,archehr_train,archehr_17,What should he do to relieve palpitations and ...,Palpitations may occur if sleep apnea is untre...,The patient was started on levothyroxine and s...,Correct,Incorrect,The generated answer does not address relievin...
6,R07,bioasq_train,bioasq13b_623648513a8413c6530000ae,What is Abbreviated Injury Scale (AIS) used to...,The Abbreviated Injury Scale (AIS) is an objec...,The Abbreviated Injury Scale (AIS) is used to ...,Correct,Incorrect,The generated answer inaccurately limits AIS t...
8,R09,bioasq_train,bioasq13b_5a43a933966455904c00000b,How may CTCF mediate splicing?,Two different mechanisms convey DNA methylatio...,CTCF mediates splicing by promoting inclusion ...,Correct,Incorrect,unsupported claim about oxidation derivatives
10,R11,bioasq_train,bioasq13b_56a3a6c9496b62f23f000008,What is TFBSshape?,To utilize DNA shape information when analysin...,TFBSshape is a motif database for DNA shape fe...,Incorrect,Correct,The generated answer accurately describes TFBS...
12,R13,archehr_train,archehr_14,Was there any evidence for stomach cancer?,The patient does not have any evidence of stom...,The evidence does not address stomach cancer. ...,Correct,Incorrect,The generated answer does not directly address...
19,R20,bioasq_train,bioasq13b_606b61f794d57fd879000068,What is known about natriuretic peptide recept...,Atrial natriuretic peptide (ANP) and its natri...,"Natriuretic peptide receptor A (NPRA), also kn...",Correct,Incorrect,The generated answer claims that the downstrea...
20,R21,archehr_train,archehr_6,Why did they find out later that he had fungal...,Preliminary tests showed Candida infection in ...,The evidence indicates that *Torulopsis glabra...,Correct,Incorrect,generated answer contains unsupported claims a...
25,R26,archehr_train,archehr_3,What is the expected course of recovery for him?,"This patient should expect to have drowsiness,...","Some symptoms following a head injury, such as...",Correct,Incorrect,omitted major parts of the expected course of ...
26,R27,bioasq_train,bioasq13b_530cf22aa177c6630c000001,What is the role of Inn1 in cytokinesis?,Inn1 associates with the contractile actomyosi...,Inn1 plays a role in cytokinesis by regulating...,Correct,Incorrect,generated answer introduces unsupported claims...
27,R28,bioasq_train,bioasq13b_5c6585097c78d69471000003,What is the function of the Nup153 protein?,Nup153 is a large (153 kD) O-linked glyco-prot...,Nup153 plays pivotal roles in nuclear pore fun...,Correct,Incorrect,unsupported claims about regulating cardiac ge...
31,R32,bioasq_train,bioasq13b_587e42032420191125000004,What is MINDY-1?,MINDY-1 (motif interacting with Ub-containing ...,MINDY-1 is a member of a newly discovered fami...,Correct,Incorrect,generated answer introduces unsupported claim ...
36,R37,archehr_train,archehr_8,Will the poison damage to his body last and is...,Patient has cirrhosis due to alcohol abuse [45...,Treatment included hydration and medications t...,Correct,Incorrect,The generated answer does not address if the p...

#### 2) Case Review of the Four Profiles

Exploratory case-level review to examine the evidence and answer patterns underlying the four profiles.

In [12]:
heldout = pd.read_csv(HELDOUT_PATH)

profiles = [
    "Stable–Stable",
    "Stable–Variable",
    "Unstable–Stable",
    "Unstable–Variable",
]

selected_cases = []

for profile in profiles:
    group = heldout[
        heldout["joint_profile"] == profile
    ]

    sampled = group.sample(
        n=1,
        random_state=42,
    )

    selected_cases.append(sampled)

selected_cases = pd.concat(
    selected_cases,
    ignore_index=True,
)

display(
    selected_cases[
        [
            "case_id",
            "joint_profile",
            "evidence_uncertainty",
            "answer_uncertainty",
            "judge_correct",
        ]
    ]
)

,case_id,joint_profile,evidence_uncertainty,answer_uncertainty,judge_correct
0,archehr_66,Stable–Stable,0.000000,-0.000000,1
1,archehr_23,Stable–Variable,0.000000,0.217322,1
2,archehr_52,Unstable–Stable,0.177778,-0.000000,0
3,archehr_88,Unstable–Variable,0.084040,0.518352,0

In [13]:
# Load the detailed held-out outputs
selected_ids = selected_cases["case_id"].tolist()

evidence_runs = pd.DataFrame(
    load_jsonl(HELDOUT_DIR / "evidence_runs.jsonl")
)

evidence_summary = pd.read_csv(
    HELDOUT_DIR / "evidence_summary.csv"
)

answer_runs = pd.read_csv(
    HELDOUT_DIR / "answer_runs_with_clusters.csv"
)

judge_results = pd.DataFrame(
    load_jsonl(HELDOUT_DIR / "judge_results.jsonl")
)

cases = load_jsonl(
    PROCESSED_DIR / "archehr_test_cases.jsonl"
)

case_lookup = {
    case["case_id"]: case
    for case in cases
}

In [ ]:
for case_id in selected_ids:

    case = case_lookup[case_id]

    print("=="*5)
    print(case_id)
    print("=="*5)

    print("\n[QUESTION]")
    print(case["question"])

    print("\n[REFERENCE ANSWER]")
    print(case["reference_answers"][0])

    print("\n[EVIDENCE SELECTION RUNS]")
    display(
        evidence_runs[
            evidence_runs["case_id"] == case_id
        ][
            [
                "run_id",
                "selected_sentence_ids",
            ]
        ]
    )

    summary = evidence_summary[
        evidence_summary["case_id"] == case_id
    ].iloc[0]

    representative_ids = json.loads(
        summary["selected_sentence_ids"]
    )

    print("\n[REPRESENTATIVE EVIDENCE]")
    for sentence in case["sentences"]:
        if str(sentence["sentence_id"]) in set(
            map(str, representative_ids)
        ):
            print(
                f'[{sentence["sentence_id"]}] '
                f'{sentence["text"]}'
            )

    print("\n[ANSWER RUNS]")
    display(
        answer_runs[
            answer_runs["case_id"] == case_id
        ][
            [
                "run_id",
                "cluster_label",
                "answer",
            ]
        ]
    )

    print("\n[LLM JUDGE]")
    display(
        judge_results[
            judge_results["case_id"] == case_id
        ][
            [
                "correct",
                "representative_answer",
                "reason",
            ]
        ]
    )

==========
archehr_66
==========

[QUESTION]
How were the goals of care established?

[REFERENCE ANSWER]
Patient with squamous cell cervical cancer, s/p combined chemoradiation with nephrostomy tube presented with dark stools and drop in her Hct. Patient found to have new pulmonary metastases and early cardiac tamponade. During a meeting with her family and social work, the patient made the decision that she did not want to undergo any more chemotherapy or invasive therapies including pericardiocentesis. The patient will be discharged to hospice with a focus on comfort.

[EVIDENCE SELECTION RUNS]

     run_id selected_sentence_ids
450       0     [3, 7, 9, 11, 17]
451       1     [3, 7, 9, 11, 17]
452       2     [3, 7, 9, 11, 17]
453       3     [3, 7, 9, 11, 17]
454       4     [3, 7, 9, 11, 17]
455       5     [3, 7, 9, 11, 17]
456       6     [3, 7, 9, 11, 17]
457       7     [3, 7, 9, 11, 17]
458       8     [3, 7, 9, 11, 17]
459       9     [3, 7, 9, 11, 17]

[REPRESENTATIVE EVIDENCE]
[3] # Goals of care discussion - After it was determined that the patient had signs of cardiac tamponade, family meetings were held with the patient, her husband, daughters, and palliative care.
[7] Patient was never HD unstable - this finding prompted goals of care discussion as above given need of pericardiocentesis and then window if treatment desired.
[9] There was an initial plan to attempt further laser therapy, but this was decided against after the goals of care discussions.
[11] The patient stated she would not want to undergo further chemotherapy.
[17] After discussion with you and your family, it was decided to focus on treating your symptoms and alleviating suffering.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                                                                                                         answer
450       0              0                                                                                              Goals of care were established after signs of cardiac tamponade were noted and family meetings were held with the patient, her husband, and daughters, including palliative care. Further laser therapy and chemotherapy were decided against following these discussions, and the focus shifted to symptom management and alleviating suffering.
451       1              0                                                                 Goals of care were established after it was determined the patient had signs of cardiac tamponade and prompted family meetings involving the patient, her husband, and daughters, with palliative care. Further laser therapy and chemotherapy were ruled out following these discussions, and the decision was made to focus on symptom management and alleviating suffering.
452       2              0                                                                           Goals of care were established after signs of cardiac tamponade were noted and discussions were held with the patient, her husband, and daughters, including palliative care. The decision to focus on symptom management and alleviating suffering was made after discussions with the patient's family, and further laser therapy and chemotherapy were ruled out.
453       3              0                                                                                                  Goals of care were established after signs of cardiac tamponade were noted and discussions were held with the patient, her husband, and daughters, including palliative care. Further laser therapy and chemotherapy were decided against following these discussions, and the focus shifted to symptom management and alleviating suffering.
454       4              0                                                                                              Goals of care were established after signs of cardiac tamponade were noted and family meetings were held with the patient, her husband, and daughters, including palliative care. Further laser therapy and chemotherapy were decided against following these discussions, and the focus shifted to symptom management and alleviating suffering.
455       5              0                                                                                           Goals of care were established after signs of cardiac tamponade were noted and discussions were held with the patient, her husband, and daughters, including palliative care. Further laser therapy and chemotherapy were ruled out following these discussions, and the decision was made to focus on symptom management and alleviating suffering.
456       6              0                                                                  Goals of care were established after it was determined the patient had signs of cardiac tamponade and prompted family meetings involving the patient, her husband, and daughters, as well as palliative care. Further laser therapy and chemotherapy were decided against following these discussions, and the focus shifted to symptom management and alleviating suffering.
457       7              0                                                                        Goals of care were established after signs of cardiac tamponade were noted and discussions were held with the patient, her husband, and daughters, including palliative care. Initially, further laser therapy was considered, but this was decided against following these discussions. Ultimately, the focus shifted to symptom management and alleviating suffering.
458       8              0                                                                                                  Goals of care were established after signs of cardiac tamponade were noted and discussions were held with the patient, her husband, and daughters, including palliative care. Further laser therapy and chemotherapy were ruled out following these discussions, and it was decided to focus on symptom management and alleviating suffering.
459       9              0  Goals of care were established after signs of cardiac tamponade were noted, prompting discussions with the patient, her husband, and daughters, involving palliative care. Initially, further laser therapy was considered, but this was abandoned following these discussions. Ultimately, the decision was made to focus on symptom management and alleviating suffering, aligning with the patient's desire to forgo further chemotherapy.

[LLM JUDGE]

    correct                                                                                                                                                                                                                                                                                                                              representative_answer                                                                                                                                                         reason
45     True  Goals of care were established after signs of cardiac tamponade were noted and family meetings were held with the patient, her husband, and daughters, including palliative care. Further laser therapy and chemotherapy were decided against following these discussions, and the focus shifted to symptom management and alleviating suffering.  The generated answer accurately captures the establishment of care goals through family meetings and the decision to focus on comfort and symptom management.

==========
archehr_23
==========

[QUESTION]
Why was she given antibiotics during her hospital stay?

[REFERENCE ANSWER]
The patient was given antibiotics during her hospital stay because of a lung infection. The patient was noted to have low levels of oxygen and a chest x-ray was ordered. it indicated the patient was developing pneumonia. IV antibiotics were initiated to treat the pneumonia. The patient showed improvement right away after starting the antibiotics. Therefore, the antibiotics were necessary during her hospital stay.

[EVIDENCE SELECTION RUNS]

    run_id selected_sentence_ids
20       0                [5, 6]
21       1                [5, 6]
22       2                [5, 6]
23       3                [5, 6]
24       4                [5, 6]
25       5                [5, 6]
26       6                [5, 6]
27       7                [5, 6]
28       8                [5, 6]
29       9                [5, 6]

[REPRESENTATIVE EVIDENCE]
[5] On [**2174-2-11**], it was noted that you were not holding your oxygen levels as high as we would like so a chest x-ray was done, and indicated that you were developing a pneumonia.
[6] We started IV antibiotics for this right away, and you improved.

[ANSWER RUNS]

    run_id  cluster_label                                                                                                                                                                                                                                                                         answer
20       0              0                                                                              Antibiotics were initiated on [2174-2-11] because a chest x-ray indicated the development of pneumonia. The patient’s condition improved following the administration of intravenous antibiotics.
21       1              0                                                                                     Antibiotics were initiated intravenously because a chest x-ray on February 11, 2024, indicated the patient was developing pneumonia. The patient improved after receiving the antibiotics.
22       2              0                                                                                    Antibiotics were initiated on 2174-2-11 due to a developing pneumonia indicated by a chest x-ray. The patient's condition improved following the administration of intravenous antibiotics.
23       3              0                                                                        Antibiotics were initiated intravenously because a chest x-ray on February 11, 2024, indicated the patient was developing pneumonia. The patient subsequently improved after receiving the antibiotics.
24       4              1                          Antibiotics were initiated on 2174-2-11 because a chest x-ray indicated the patient was developing pneumonia. Oxygen levels were not being maintained as desired prior to this finding. The patient improved after receiving intravenous antibiotics.
25       5              0                                                                                            Antibiotics were initiated intravenously because a chest x-ray on [2174-2-11] indicated the patient was developing pneumonia. The patient improved after receiving the antibiotics.
26       6              0                                                                              Antibiotics were initiated on [2174-2-11] because a chest x-ray indicated the development of pneumonia. The patient’s condition improved following the administration of intravenous antibiotics.
27       7              1  Antibiotics were initiated on February 11, 2174, because a chest x-ray indicated the development of pneumonia. Your oxygen levels were not being maintained as desired prior to treatment. You subsequently improved following the administration of intravenous antibiotics.
28       8              0                                                                              Antibiotics were initiated on [2174-2-11] because a chest x-ray indicated the development of pneumonia. The patient’s condition improved following the administration of intravenous antibiotics.
29       9              0                                                                            Antibiotics were initiated intravenously because a chest x-ray on [2174-2-11] indicated the development of pneumonia. The patient demonstrated improvement following the initiation of antibiotics.

[LLM JUDGE]

   correct                                                                                                                                                                              representative_answer                                                                                                             reason
2     True  Antibiotics were initiated on [2174-2-11] because a chest x-ray indicated the development of pneumonia. The patient’s condition improved following the administration of intravenous antibiotics.  The generated answer accurately states the reason for antibiotics and the improvement in the patient's condition.

==========
archehr_52
==========

[QUESTION]
What should he do for persistent lightheadedness?

[REFERENCE ANSWER]
Patient might have had encephalitis, but no specific cause was found at the time of discharge. Based on the discharge instructions, there are still some tests pending. If his lightheadedness is intermittent, he should just follow up with the neurology clinic as scheduled. However, if the lightheadedness is persistent and/or if he develops a fever, he should call the neurology clinic to help determine if he should present to the ER.

[EVIDENCE SELECTION RUNS]

     run_id selected_sentence_ids
310       0                [3, 5]
311       1                [3, 5]
312       2                [3, 5]
313       3             [3, 4, 5]
314       4             [3, 4, 5]
315       5                [3, 5]
316       6                [3, 5]
317       7                [3, 5]
318       8             [3, 4, 5]
319       9             [3, 4, 5]

[REPRESENTATIVE EVIDENCE]
[3] We did not find a specific cause at the time of discharge.
[5] If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                answer
310       0              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
311       1              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
312       2              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
313       3              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
314       4              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
315       5              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
316       6              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
317       7              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
318       8              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
319       9              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.

[LLM JUDGE]

    correct                                                                                                                                                 representative_answer                                                    reason
31    False  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.  omitted specific guidance for persistent lightheadedness

==========
archehr_88
==========

[QUESTION]
What is her expected course of recovery?

[REFERENCE ANSWER]
Patient admitted for back pain. Imaging found multiple abscesses in her spine and right knee, which required several surgeries and antibiotics to treat the infections. Antibiotics changed several times due to significant adverse reactions. Course of antibiotics to run for 8 weeks; so a PICC line was placed for outpatient treatment. Patient noted to have silent aspiration and started on thickened liquids which will require a speech and swallow consult at rehab before advancing diet.

[EVIDENCE SELECTION RUNS]

     run_id                  selected_sentence_ids
670       0  [4, 5, 6, 26, 27, 28, 29, 30, 32, 41]
671       1   [2, 4, 5, 6, 26, 27, 28, 29, 30, 32]
672       2   [2, 4, 5, 6, 26, 27, 28, 29, 30, 32]
673       3   [2, 4, 5, 6, 26, 27, 28, 29, 30, 32]
674       4   [2, 4, 5, 6, 26, 27, 28, 29, 30, 32]
675       5   [2, 4, 5, 6, 26, 27, 28, 29, 30, 32]
676       6  [4, 5, 6, 26, 27, 28, 29, 30, 32, 41]
677       7      [4, 5, 6, 26, 27, 28, 29, 30, 32]
678       8   [2, 4, 5, 6, 26, 27, 28, 29, 30, 32]
679       9      [4, 5, 6, 26, 27, 28, 29, 30, 32]

[REPRESENTATIVE EVIDENCE]
[2] # Bacteremia/Abscesses/Antibiotic therapy
[4] CBC with noted leukopenia on [**8-5**] with progression to neutropenia [**8-8**].
[5] Out of concern that vancomycin could be contributing to decreasing counts, vanc d/c'ed and IV daptomycin started.
[6] Per ID will plan to treat MSSA bacteremia/abscesses with IV daptomycin to total of 6-8wk course.
[26] Upon imaging it was found that you had several abscesses throughout your spine as well as in your right knee.
[27] You underwent several surgeries to evacuate these infection and you were also started on antibiotics.
[28] Your antibiotic regimen was altered several times due to significant side effects.
[29] You experienced a rash after Nafcillin, and Vancomyocin was thought to contribute to low cell counts.
[30] You were placed on Daptomycin without side effect for a planned 8week course.
[32] You will receive repeat imaging after completion of your antibiotic therapy for interval evaluation of infection.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                                                                                                       answer
670       0              1                                                  The patient is receiving a 6-8 week course of IV daptomycin to treat MSSA bacteremia and abscesses in the spine and right knee, following surgical evacuation of the abscesses. Repeat imaging will be performed after completion of antibiotic therapy to evaluate the infection. The patient previously experienced leukopenia and neutropenia, prompting a change in antibiotic regimen.
671       1              2                                                                                            Your mother's recovery will involve repeat imaging after completion of a planned 8-week course of IV daptomycin to treat MSSA bacteremia/abscesses. These abscesses were found throughout her spine and right knee, and she underwent surgeries to evacuate the infections. Her antibiotic regimen was altered several times due to side effects.
672       2              1                                                                                                                 The patient is receiving a 6-8 week course of IV daptomycin to treat MSSA bacteremia/abscesses in the spine and knee. Repeat imaging will be performed after completion of antibiotic therapy to evaluate the infection. Previous antibiotics, including nafcillin and vancomycin, were discontinued due to adverse effects.
673       3              1                                                                               The patient is receiving a 6-8 week course of IV daptomycin to treat MSSA bacteremia and abscesses in the spine and knee. Repeat imaging will be performed after completion of antibiotic therapy to evaluate the infection. Her antibiotic regimen has been altered due to side effects, including a rash with nafcillin and low cell counts with vancomycin.
674       4              0                                                                                                      Your current treatment plan involves a 6-8 week course of IV daptomycin for MSSA bacteremia/abscesses. Repeat imaging will be performed after completion of antibiotic therapy to evaluate the infection. You previously experienced leukopenia and neutropenia, and vancomycin was discontinued due to concerns about low cell counts.
675       5              3                                                                                                                                                    Your current treatment plan involves a 6-8 week course of IV daptomycin for MSSA bacteremia/abscesses. Repeat imaging will be performed after completion of antibiotic therapy to evaluate the infection. The cause of your continued fever is not specified in the provided information.
676       6              0                                                                                                                                                                          Your current course of recovery involves a planned 6-8 week course of IV daptomycin to treat MSSA bacteremia and abscesses throughout your spine and right knee. Repeat imaging will be performed after completion of antibiotic therapy to evaluate the infection.
677       7              0                                                                                Your current course of recovery involves a planned 6-8 week course of IV daptomycin to treat MSSA bacteremia and abscesses throughout your spine and right knee. Repeat imaging will be performed after completion of antibiotic therapy to evaluate the infection. You previously experienced leukopenia and neutropenia, prompting a change in antibiotics.
678       8              0                                                                                                  Your current course of recovery involves a planned 6-8 week course of IV daptomycin to treat MSSA bacteremia/abscesses. Repeat imaging will be performed after completion of antibiotic therapy to evaluate the infection. You previously experienced leukopenia and neutropenia, and antibiotic regimens were altered due to side effects.
679       9              1  The patient is receiving a 6-8 week course of IV daptomycin to treat MSSA bacteremia and abscesses in the spine and knee, following surgeries to evacuate the infections. Repeat imaging will be performed after completion of antibiotic therapy to evaluate for interval infection. The patient previously experienced leukopenia and neutropenia, and vancomycin was discontinued due to concerns about contributing to low cell counts.

[LLM JUDGE]

    correct                                                                                                                                                                                                                                                                                                                                                                        representative_answer                                                reason
67    False  The patient is receiving a 6-8 week course of IV daptomycin to treat MSSA bacteremia and abscesses in the spine and right knee, following surgical evacuation of the abscesses. Repeat imaging will be performed after completion of antibiotic therapy to evaluate the infection. The patient previously experienced leukopenia and neutropenia, prompting a change in antibiotic regimen.  inconsistent information and omission of key details

#### 3) Evidence-Selection and Answer-Generation Variability in Relation to Answer Error

Exploratory review to examine case-level patterns of evidence-selection and answer-generation variability in relation to answer error.

In [15]:
# Define the six groups and randomly sample three cases from each
heldout = pd.read_csv(HELDOUT_PATH)

review_groups = [
    ("Unstable–Variable incorrect", "Unstable–Variable", 0),
    ("Stable–Stable incorrect", "Stable–Stable", 0),
    ("Unstable–Stable incorrect", "Unstable–Stable", 0),
    ("Stable–Variable incorrect", "Stable–Variable", 0),
    ("Unstable–Stable correct", "Unstable–Stable", 1),
    ("Stable–Variable correct", "Stable–Variable", 1),
]

selected_review_cases = []

for group_name, profile, correct in review_groups:

    group = heldout[
        (heldout["joint_profile"] == profile)
        & (heldout["judge_correct"] == correct)
    ]

    sampled = group.sample(
        n=3,
        random_state=42,
    ).copy()

    sampled["review_group"] = group_name

    selected_review_cases.append(sampled)

selected_review_cases = pd.concat(
    selected_review_cases,
    ignore_index=True,
)

assert len(selected_review_cases) == 18

display(
    selected_review_cases[
        [
            "case_id",
            "review_group",
            "joint_profile",
            "evidence_uncertainty",
            "answer_uncertainty",
            "judge_correct",
        ]
    ]
)

        case_id                 review_group      joint_profile  evidence_uncertainty  answer_uncertainty  judge_correct
0    archehr_51  Unstable–Variable incorrect  Unstable–Variable              0.204918            0.348225              0
1    archehr_54  Unstable–Variable incorrect  Unstable–Variable              0.186420            0.217322              0
2    archehr_71  Unstable–Variable incorrect  Unstable–Variable              0.330823            0.301030              0
3    archehr_82      Stable–Stable incorrect      Stable–Stable              0.000000           -0.000000              0
4   archehr_101      Stable–Stable incorrect      Stable–Stable              0.000000           -0.000000              0
5    archehr_25      Stable–Stable incorrect      Stable–Stable              0.000000           -0.000000              0
6    archehr_21    Unstable–Stable incorrect    Unstable–Stable              0.132593           -0.000000              0
7    archehr_43    Unstable–Stable incorrect    Unstable–Stable              0.050000           -0.000000              0
8    archehr_52    Unstable–Stable incorrect    Unstable–Stable              0.177778           -0.000000              0
9    archehr_42    Stable–Variable incorrect    Stable–Variable              0.000000            0.277528              0
10   archehr_28    Stable–Variable incorrect    Stable–Variable              0.000000            0.141182              0
11   archehr_93    Stable–Variable incorrect    Stable–Variable              0.000000            0.590309              0
12   archehr_34      Unstable–Stable correct    Unstable–Stable              0.025000           -0.000000              1
13   archehr_74      Unstable–Stable correct    Unstable–Stable              0.294025           -0.000000              1
14   archehr_24      Unstable–Stable correct    Unstable–Stable              0.237037           -0.000000              1
15   archehr_26      Stable–Variable correct    Stable–Variable              0.000000            0.277528              1
16   archehr_95      Stable–Variable correct    Stable–Variable              0.000000            0.217322              1
17   archehr_23      Stable–Variable correct    Stable–Variable              0.000000            0.217322              1

In [17]:
# Review the selected 18 cases

selected_ids = selected_review_cases[
    "case_id"
].tolist()

for case_id in selected_ids:

    case = case_lookup[case_id]

    print("=="*5)
    print(case_id)
    print("=="*5)

    print("\n[QUESTION]")
    print(case["question"])

    print("\n[REFERENCE ANSWER]")
    print(case["reference_answers"][0])

    print("\n[EVIDENCE SELECTION RUNS]")
    display(
        evidence_runs[
            evidence_runs["case_id"] == case_id
        ][
            [
                "run_id",
                "selected_sentence_ids",
            ]
        ]
    )

    summary = evidence_summary[
        evidence_summary["case_id"] == case_id
    ].iloc[0]

    representative_ids = json.loads(
        summary["selected_sentence_ids"]
    )

    print("\n[REPRESENTATIVE EVIDENCE]")
    for sentence in case["sentences"]:
        if str(sentence["sentence_id"]) in set(
            map(str, representative_ids)
        ):
            print(
                f'[{sentence["sentence_id"]}] '
                f'{sentence["text"]}'
            )

    print("\n[ANSWER RUNS]")
    display(
        answer_runs[
            answer_runs["case_id"] == case_id
        ][
            [
                "run_id",
                "cluster_label",
                "answer",
            ]
        ]
    )

    print("\n[LLM JUDGE]")
    display(
        judge_results[
            judge_results["case_id"] == case_id
        ][
            [
                "correct",
                "representative_answer",
                "reason",
            ]
        ]
    )

==========
archehr_51
==========

[QUESTION]
What should she do for her ongoing chest pain?

[REFERENCE ANSWER]
The patient has several options to manage her chest pain. The pain is likely related to the rib fracture she sustained in the MV accident. She should stay on schedule with her pain medicine regimen, and use her incentive spirometer 4 times an hour while awake to help keep her lungs clear and cough pillow as directed to help support her ribs while coughing. She can also use heat or cold packs for pain relief.

[EVIDENCE SELECTION RUNS]

     run_id                                                                                                                     selected_sentence_ids
300       0  [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]
301       1      [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]
302       2          [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 66]
303       3      [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]
304       4      [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]
305       5                                                              [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 61, 62]
306       6                                                          [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 61, 62]
307       7          [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 66]
308       8          [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 66]
309       9                                                              [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 61, 62]

[REPRESENTATIVE EVIDENCE]
[33] ** Rib Fracture *
[34] Your injury caused a right 1st rib fracture which can cause severe pain and subsequently cause you to take shallow breaths because of the pain.
[35] *
[36] You should take your pain medication as directed to stay ahead of the pain otherwise you won't be able to take deep breaths.
[37] If the pain medication is too sedating take half the dose and notify your physician.
[38] * Pneumonia is a complication of rib fractures.
[39] In order to decrease your risk you must use your incentive spirometer 4 times every hour while awake.
[40] This will help expand the small airways in your lungs and assist in coughing up secretions that pool in the lungs.
[41] *
[42] You will be more comfortable if you use a cough pillow to hold against your chest and guard your rib cage while coughing and deep breathing.
[43] * Symptomatic relief with ice packs or heating pads for short periods may ease the pain.
[44] * Narcotic pain medication can cause constipation therefore you should take a stool softener twice daily and increase your fluid and fiber intake if possible.
[45] * Do NOT smoke *
[46] Non-steroidal anti-inflammatory drugs are very effective in controlling pain ( ie, Ibuprofen, Motrin, Advil, Aleve, Naprosyn).
[47] * Return to the Emergency Room right away for any acute shortness of breath, increased pain or crackling sensation around your ribs (crepitus).
[48] - Please call your doctor or nurse practitioner or return to the Emergency Department for any of the following: * You experience new chest pain, pressure, squeezing or tightness.
[50] New or worsening cough, shortness of breath, or wheeze.
[51] *
[52] If you are vomiting and cannot keep down fluids or your medications.
[53] *
[54] You are getting dehydrated due to continued vomiting, diarrhea, or other reasons.
[55] Signs of dehydration include dry mouth, rapid heartbeat, or feeling dizzy or faint when standing.
[56] *
[57] You see blood or dark/black material when you vomit or have a bowel movement.
[58] *
[59] You experience burning when you urinate, have blood in your urine, or experience a discharge.
[60] *
[61] Your pain in not improving within ___ hours or is not gone within 24 hours.
[62] Call or return immediately if your pain is getting worse or changes location or moving to your chest or back.
[63] *
[64] You have shaking chills, or fever greater than 101.5 degrees Fahrenheit or 38 degrees Celsius.
[66] Any change in your symptoms, or any new symptoms that concern you.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                        answer
300       0              2                                                   Please call your doctor or return to the Emergency Department if you experience new chest pain, pressure, squeezing, or tightness. Also, seek immediate care if your pain is getting worse or changes location, moving to your chest or back, or if you have a fever greater than 101.5 degrees Fahrenheit.
301       1              0  Please call your doctor or return to the Emergency Department if you experience new chest pain, pressure, squeezing, or tightness. Return immediately if your pain is getting worse or changes location, moving to your chest or back. Also, seek immediate care for any acute shortness of breath, increased pain, or crackling sensation around your ribs.
302       2              0                               Please call your doctor or return to the Emergency Department if you experience new chest pain, pressure, squeezing, or tightness. Also, seek immediate care if your pain is getting worse or changes location, moving to your chest or back. Return to the Emergency Room for any acute shortness of breath or increased pain.
303       3              1                                                        You should take pain medication as directed to manage chest pain and allow for deep breaths. If the medication is too sedating, take half the dose and notify your physician. Please call your doctor or return to the Emergency Department for any new chest pain, pressure, squeezing, or tightness.
304       4              0                                         Please call your doctor or return to the Emergency Department if you experience new chest pain, pressure, squeezing, or tightness. Also, seek immediate care if your pain is getting worse or changes location, moving to your chest or back. Return immediately for any acute shortness of breath or increased pain.
305       5              0  Please call your doctor or return to the Emergency Department if you experience new chest pain, pressure, squeezing, or tightness. Return immediately if your pain is getting worse or changes location, moving to your chest or back. Also, seek immediate care for any acute shortness of breath, increased pain, or crackling sensation around your ribs.
306       6              0  Please call your doctor or return to the Emergency Department if you experience new chest pain, pressure, squeezing, or tightness. Return immediately if your pain is getting worse or changes location, moving to your chest or back. Also, seek immediate care for any acute shortness of breath, increased pain, or crackling sensation around your ribs.
307       7              0  Please call your doctor or return to the Emergency Department if you experience new chest pain, pressure, squeezing, or tightness. Also, seek immediate care if your pain is getting worse or changes location, moving to your chest or back. Return immediately for any acute shortness of breath, increased pain, or crackling sensation around your ribs.
308       8              2                                                   Please call your doctor or return to the Emergency Department if you experience new chest pain, pressure, squeezing, or tightness. Also, seek immediate care if your pain is getting worse or changes location, moving to your chest or back, or if you have a fever greater than 101.5 degrees Fahrenheit.
309       9              0  Please call your doctor or return to the Emergency Department if you experience new chest pain, pressure, squeezing, or tightness. Return immediately if your pain is getting worse or changes location, moving to your chest or back. Also, seek immediate care for any acute shortness of breath, increased pain, or crackling sensation around your ribs.

[LLM JUDGE]

    correct                                                                                                                                                                                                                                                                                                                                         representative_answer                                                                                                                                                  reason
30    False  Please call your doctor or return to the Emergency Department if you experience new chest pain, pressure, squeezing, or tightness. Return immediately if your pain is getting worse or changes location, moving to your chest or back. Also, seek immediate care for any acute shortness of breath, increased pain, or crackling sensation around your ribs.  The generated answer does not address the management of ongoing chest pain, but instead focuses on when to seek immediate care for worsening symptoms.

==========
archehr_54
==========

[QUESTION]
Is his fever and lower abdomen pain expected while taking Levaquin, Tamiflu, and prednisone?

[REFERENCE ANSWER]
Abdominal pain is a side effect of tamiflu (per FDA), and can be relieved by taking it with a meal. The patient was instructed to take acetaminophen every 8 hours for fever management. Nausea and abdominal discomfort can be side effects of the flu, so it will be important for the patient to monitor their abdominal pain and to seek medical attention if it does not resolve after completing the levaquin, tamiflu and prednisone.

[EVIDENCE SELECTION RUNS]

     run_id                   selected_sentence_ids
330       0          [2, 7, 12, 13, 17, 18, 33, 36]
331       1                  [2, 7, 12, 13, 17, 18]
332       2      [2, 7, 12, 13, 16, 17, 18, 33, 36]
333       3                  [2, 7, 12, 13, 17, 18]
334       4      [2, 7, 12, 13, 16, 17, 18, 33, 36]
335       5  [2, 7, 12, 13, 16, 17, 18, 33, 36, 38]
336       6      [2, 7, 12, 13, 16, 17, 18, 33, 36]
337       7      [2, 7, 12, 13, 16, 17, 18, 33, 36]
338       8          [2, 7, 12, 13, 17, 18, 33, 36]
339       9                  [2, 7, 12, 13, 17, 18]

[REPRESENTATIVE EVIDENCE]
[2] # Influenza # Increased O2 requirement # COPD exacerbation Patient found to be Flu A Positive (his clinical presentation of fever, cough, malaise, myalgias, and diarrhea is consistent) and was started on Tamiflu in the ED.
[7] During this admission he was started on prednisone 40mg QD, levofloxacin 750mg QD, and oseltamivir for treatment of COPD and flu, plan to complete ___s outpatient.
[12] To finish prednisone and levofloxacin for 5 day course (finish ___. []
[13] To finish four more days of Tamiflu (finish ___. []
[16] Discharge Medications:Medications: 1. Acetaminophen 1000 mg PO Q8H:PRN Pain - Mild/Fever RX *acetaminophen 500 mg 2 tablet(s) by mouth three times a day Disp #*20 Tablet Refills:*0 2.
[17] GuaiFENesin ___ mL PO Q6H:PRN cough RX *guaifenesin 600 mg 1 tablet by mouth twice a day Disp #*20 Tablet Refills:*0 3. Levofloxacin 750 mg PO DAILY Duration: 4 Doses RX *levofloxacin 750 mg 1 tablet(s) by mouth once a day Disp #*3 Tablet Refills:*0 4. OSELTAMivir 75 mg PO BID RX *oseltamivir 75 mg 1 capsule(s) by mouth twice a day Disp #*8 Capsule Refills:*0 5.
[18] PredniSONE 40 mg PO DAILY Duration: 4 Doses RX *prednisone 20 mg 2 tablet(s) by mouth once a day Disp #*6 Tablet Refills:*0 6.
[33] - ___ were given Tamiflu to treat the flu. - ___ were given antibiotics and prednisone to treat for a COPD exacerbation.
[36] - Please continue to take the Tamiflu, prednisone, and antibiotic as prescribed.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                                       answer
330       0              0                  The patient's fever, cough, malaise, myalgias, and diarrhea are consistent with influenza, which is being treated with Tamiflu. He is also receiving prednisone and levofloxacin for a COPD exacerbation. The plan is to complete the prescribed courses of prednisone and levofloxacin, as well as Tamiflu. Continue taking all medications as prescribed.
331       1              0  The patient's fever, cough, malaise, myalgias, and diarrhea are consistent with influenza, which is being treated with Tamiflu. The patient is also taking prednisone and levofloxacin for a COPD exacerbation. The evidence does not indicate whether the lower abdominal pain is expected with these medications. Continue taking all prescribed medications as directed.
332       2              0                                  The patient's fever, cough, malaise, myalgias, and diarrhea are consistent with influenza, which is treated with Tamiflu. He was also prescribed prednisone and levofloxacin for a COPD exacerbation. The plan is to complete a 5-day course of levofloxacin and four more days of Tamiflu. Acetaminophen is prescribed for pain and fever.
333       3              0                              The patient's fever, cough, malaise, myalgias, and diarrhea are consistent with influenza, which is treated with Tamiflu. He was also prescribed prednisone and levofloxacin for a COPD exacerbation. The patient should continue taking Tamiflu, prednisone, and the antibiotic as prescribed. Acetaminophen is prescribed for pain and fever.
334       4              0             The patient's fever, cough, malaise, and myalgias are consistent with influenza, which is being treated with Tamiflu. He is also taking prednisone and levofloxacin for a COPD exacerbation. The evidence does not explicitly state whether the lower abdominal pain is expected with these medications. Continue taking all prescribed medications as directed.
335       5              1            The patient's fever, cough, malaise, myalgias, and diarrhea are consistent with influenza, which is being treated with Tamiflu. He is also receiving prednisone and levofloxacin for a COPD exacerbation. The prescribed duration for levofloxacin is 4 days, and Tamiflu for 4 days, with prednisone for 4 days. Acetaminophen is prescribed for pain and fever.
336       6              0                     The patient's fever, cough, malaise, myalgias, and diarrhea are consistent with influenza, which is being treated with Tamiflu. Prednisone and levofloxacin are being administered for a COPD exacerbation. The patient should continue taking all prescribed medications as directed, including Tamiflu, prednisone, and the antibiotic (levofloxacin).
337       7              1               The patient's fever, cough, malaise, myalgias, and diarrhea are consistent with influenza, which is treated with Tamiflu. The patient was also prescribed prednisone and levofloxacin for a COPD exacerbation. The prescribed duration for levofloxacin is 4 days, Tamiflu is 4 days, and prednisone is 4 days. Continue taking all medications as prescribed.
338       8              0                     The patient's fever, cough, malaise, myalgias, and diarrhea are consistent with influenza, which is being treated with Tamiflu. The patient is also taking prednisone and levofloxacin for a COPD exacerbation. The plan is to complete the prescribed courses of prednisone, levofloxacin, and Tamiflu. Acetaminophen is prescribed for pain and fever.
339       9              0                                     The patient's fever, cough, malaise, myalgias, and diarrhea are consistent with influenza, which is treated with Tamiflu. The patient was also prescribed prednisone and levofloxacin for a COPD exacerbation. Continue taking all prescribed medications as directed, including Tamiflu, prednisone, and the antibiotic (levofloxacin).

[LLM JUDGE]

    correct                                                                                                                                                                                                                                                                                                                                        representative_answer                                                                                                                                                                                                                                        reason
33    False  The patient's fever, cough, malaise, myalgias, and diarrhea are consistent with influenza, which is being treated with Tamiflu. He is also receiving prednisone and levofloxacin for a COPD exacerbation. The plan is to complete the prescribed courses of prednisone and levofloxacin, as well as Tamiflu. Continue taking all medications as prescribed.  The generated answer does not address the question about the expected side effects of the medications, specifically the fever and lower abdomen pain, and does not provide guidance on managing these symptoms as the reference answer does.

==========
archehr_71
==========

[QUESTION]
What is expected course of her recovery?

[REFERENCE ANSWER]
Patient was hospitalized due to difficulty with speech and weakness, caused by an intracranial hemorrhage due to amyloid angiopathy. She had an extensive bleed and worsening swelling. Brain monitoring showed frequent epileptiform discharges. Keppra was started to suppress these discharges but there was no clinical change. When Keppra was replaced with amantadine, the patient became more alert, awake, and verbal. Pt will be monitored for alertness and have her Amantidine up titrated as needed.

[EVIDENCE SELECTION RUNS]

     run_id                            selected_sentence_ids
500       0                         [22, 26, 27, 28, 32, 33]
501       1  [7, 14, 16, 18, 22, 26, 27, 28, 30, 32, 33, 36]
502       2          [7, 14, 16, 18, 22, 26, 27, 28, 32, 33]
503       3                             [22, 27, 28, 32, 33]
504       4      [7, 14, 16, 17, 18, 22, 26, 27, 28, 32, 33]
505       5                             [22, 27, 28, 32, 33]
506       6          [7, 14, 16, 18, 22, 26, 27, 28, 32, 33]
507       7                             [22, 27, 28, 32, 33]
508       8                         [22, 26, 27, 28, 32, 33]
509       9                         [22, 27, 28, 32, 33, 36]

[REPRESENTATIVE EVIDENCE]
[22] This medication change and the introduction of amantadine made the patient more alert and awake and she even would occasionally whisper a 1-word answer to a question asked or follow some commands like open your eyes, move your arm etc.
[26] Discharge Condition:
[27] Mental Status: Clear and coherent.
[28] Level of Consciousness: Alert and interactive.
[32] You were hospitalized due to SPEECH DIFFICULTY and WEAKNESS resulting from an INTRACEREBRAL HEMORRHAGE (intraparenchymal hemorrhage).
[33] This bleed is thought to be due to AMYLOID ANGIOPATHY, a condition where the blood vessels become more susceptible to damage with age.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                                                                            answer
500       0              0  The patient was hospitalized due to speech difficulty and weakness resulting from an intraparenchymal hemorrhage, likely caused by amyloid angiopathy. Following medication changes, the patient demonstrated improved alertness, occasionally whispered single-word answers, and followed simple commands. At discharge, the patient’s mental status was clear and coherent, and she was alert and interactive.
501       1              0                The patient's hospitalizations were due to speech difficulty and weakness resulting from an intracerebral hemorrhage, likely caused by amyloid angiopathy. There was some improvement with medication changes, including occasional one-word responses and ability to follow simple commands. At discharge, the patient's mental status was clear and coherent, and she was alert and interactive.
502       2              0     The patient's hospitalizations were due to speech difficulty and weakness resulting from an intraparenchymal hemorrhage, likely caused by amyloid angiopathy. Following medication changes, the patient demonstrated improved alertness, occasionally whispered single-word answers, and followed simple commands. At discharge, her mental status was clear and coherent, and she was alert and interactive.
503       3              0    The patient's hospitalizations were due to speech difficulty and weakness resulting from an intraparenchymal hemorrhage, likely caused by amyloid angiopathy. Following medication changes, the patient demonstrated improved alertness, occasionally whispering single-word answers and following simple commands. At discharge, her mental status was clear and coherent, and she was alert and interactive.
504       4              1                                                     Your mother was hospitalized due to speech difficulty and weakness resulting from an intraparenchymal hemorrhage, likely caused by amyloid angiopathy. Following medication changes, she occasionally whispered single-word answers and followed simple commands. Her discharge condition was clear and coherent with an alert and interactive mental status.
505       5              1            Your mother was hospitalized due to speech difficulty and weakness resulting from an intraparenchymal hemorrhage, likely due to amyloid angiopathy. Following medication changes, she demonstrated improved alertness, occasionally whispered single-word answers, and followed simple commands. Her discharge condition was clear and coherent, with an alert and interactive level of consciousness.
506       6              1                         Your mother was hospitalized due to speech difficulty and weakness resulting from an intracerebral hemorrhage, likely caused by amyloid angiopathy. Following medication changes, she demonstrated improved alertness, occasionally whispered single-word answers, and followed some commands. At discharge, her mental status was clear and coherent, and she was alert and interactive.
507       7              1                          Your mother was hospitalized due to speech difficulty and weakness resulting from an intracerebral hemorrhage, likely caused by amyloid angiopathy. Following medication changes, she demonstrated improved alertness, occasionally whispered one-word answers, and followed simple commands. At discharge, her mental status was clear and coherent, and she was alert and interactive.
508       8              1                    Your mother was hospitalized due to speech difficulty and weakness resulting from an intraparenchymal hemorrhage, likely caused by amyloid angiopathy. Following medication changes, she demonstrated improved alertness, occasionally whispered single-word answers, and followed simple commands. At discharge, her mental status was clear and coherent, and she was alert and interactive.
509       9              0  The patient’s hospitalizations were due to speech difficulty and weakness resulting from an intraparenchymal hemorrhage, possibly caused by amyloid angiopathy. Following medication changes, the patient demonstrated improved alertness, occasionally whispering single-word answers and following simple commands. At discharge, her mental status was clear and coherent, and she was alert and interactive.

[LLM JUDGE]

    correct                                                                                                                                                                                                                                                                                                                                                                                             representative_answer                                                                              reason
50    False  The patient was hospitalized due to speech difficulty and weakness resulting from an intraparenchymal hemorrhage, likely caused by amyloid angiopathy. Following medication changes, the patient demonstrated improved alertness, occasionally whispered single-word answers, and followed simple commands. At discharge, the patient’s mental status was clear and coherent, and she was alert and interactive.  inconsistent details and missing information about the expected course of recovery

==========
archehr_82
==========

[QUESTION]
What was the course of her heart cath? What issues were associated with the groin?

[REFERENCE ANSWER]
Patient initially presented to the hospital with chest pain lasting 10 minutes. Her past medical history of hypertension and hyperlipidemia warranted further treatment. Cardiac cath procedure showed a blockage requiring a drug-eluting stent to be placed. The cath procedure was complicated by a right groin hematoma which required additional imaging. CT and ultrasound were negative for bleeding and patient was improving so no further intervention was required. At discharge, the bruise was stable.

[EVIDENCE SELECTION RUNS]

     run_id selected_sentence_ids
610       0           [8, 11, 22]
611       1           [8, 11, 22]
612       2           [8, 11, 22]
613       3           [8, 11, 22]
614       4           [8, 11, 22]
615       5           [8, 11, 22]
616       6           [8, 11, 22]
617       7           [8, 11, 22]
618       8           [8, 11, 22]
619       9           [8, 11, 22]

[REPRESENTATIVE EVIDENCE]
[8] Catherization was complicated by hypotension (likely vagal) and a groin hematoma.
[11] #Groin hematoma: The patient's cardiac catherization was complicated by a right groin hematoma.
[22] Your cardiac catherization was complicated by a bruise in your right groin.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                   answer
610       0              0                    Your cardiac catheterization was complicated by a groin hematoma. Specifically, a right groin hematoma developed, and a bruise was noted in the right groin. Hypotension, likely vagal, was also observed during the catheterization.
611       1              0              Your cardiac catheterization was complicated by a groin hematoma. Specifically, a hematoma developed in your right groin, and hypotension likely related to a vagal response also occurred. A bruise was noted in your right groin as well.
612       2              0                           Your cardiac catheterization was complicated by a groin hematoma. Specifically, a hematoma developed in your right groin. Hypotension, likely vagal, was also noted. You experienced a bruise in your right groin as a result.
613       3              0  Your cardiac catheterization was complicated by a groin hematoma. Specifically, a hematoma developed in your right groin, and hypotension likely due to a vagal response also occurred. A bruise was noted in your right groin following the procedure.
614       4              0                     Your cardiac catheterization was complicated by a groin hematoma. Specifically, a right groin hematoma occurred, and a bruise was noted in the right groin. Hypotension, likely vagal, was also observed during the catheterization.
615       5              0  Your cardiac catheterization was complicated by a groin hematoma. Specifically, a hematoma developed in your right groin, and hypotension likely due to a vagal response also occurred. A bruise was noted in your right groin following the procedure.
616       6              0                     Your cardiac catheterization was complicated by a groin hematoma. Specifically, a right groin hematoma occurred, and a bruise was noted in the right groin. Hypotension, likely vagal, was also observed during the catheterization.
617       7              0                                                Your cardiac catheterization was complicated by a groin hematoma. Specifically, a right groin hematoma occurred, and a bruise was noted in the right groin. Hypotension, likely vagal, was also observed.
618       8              0                                                                        Your cardiac catheterization was complicated by hypotension and a groin hematoma. Specifically, a right groin hematoma occurred, and there was also a bruise in your right groin.
619       9              0                                                                                             Your cardiac catheterization was complicated by hypotension and a groin hematoma. Specifically, a right groin hematoma occurred, which resulted in a bruise.

[LLM JUDGE]

    correct                                                                                                                                                                                                                  representative_answer                                                      reason
61    False  Your cardiac catheterization was complicated by a groin hematoma. Specifically, a right groin hematoma developed, and a bruise was noted in the right groin. Hypotension, likely vagal, was also observed during the catheterization.  generated answer includes unsupported claim of hypotension

==========
archehr_101
==========

[QUESTION]
Is the ileostomy permanent? Are there any plans for ileostomy reversal?

[REFERENCE ANSWER]
Based on the discharge instructions regarding ostomy teaching and management, it is likely the ileostomy will be in long term, as the patient is discharged with it and needs to learn how to manage it. This has already been a complicated course for the patient who was re-admitted after the ex-lap surgery where the ileostomy was made. Based on the information provided there is no plan for ileostomy reversal at this time.

[EVIDENCE SELECTION RUNS]

     run_id selected_sentence_ids
800       0           [2, 11, 12]
801       1           [2, 11, 12]
802       2           [2, 11, 12]
803       3           [2, 11, 12]
804       4           [2, 11, 12]
805       5           [2, 11, 12]
806       6           [2, 11, 12]
807       7           [2, 11, 12]
808       8           [2, 11, 12]
809       9           [2, 11, 12]

[REPRESENTATIVE EVIDENCE]
[2] 85F well known to the ACS service, transferred from [**Hospital 100**] rehab, 12 days s/p ex-lap, right colectomy, and end ileostomy for lower GI bleeding localized to the cecum.
[11] Please continue ostomy teaching and management.
[12] The patient has an end ileostomy and mucous fistula in place.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                               answer
800       0              0  The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not indicate whether the ileostomy is permanent or if there are plans for reversal.
801       1              0   The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not address whether the ileostomy is permanent or if there are plans for reversal.
802       2              0  The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not indicate whether the ileostomy is permanent or if there are plans for reversal.
803       3              0  The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not indicate whether the ileostomy is permanent or if there are plans for reversal.
804       4              0  The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not indicate whether the ileostomy is permanent or if there are plans for reversal.
805       5              0   The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not address whether the ileostomy is permanent or if there are plans for reversal.
806       6              0   The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not address whether the ileostomy is permanent or if there are plans for reversal.
807       7              0  The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not indicate whether the ileostomy is permanent or if there are plans for reversal.
808       8              0   The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not address whether the ileostomy is permanent or if there are plans for reversal.
809       9              0  The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not indicate whether the ileostomy is permanent or if there are plans for reversal.

[LLM JUDGE]

    correct                                                                                                                                                                                                representative_answer                                                                                                                                                  reason
80    False  The patient has an end ileostomy and mucous fistula in place. Ostomy teaching and management should continue. The evidence does not indicate whether the ileostomy is permanent or if there are plans for reversal.  The generated answer does not address whether the ileostomy is permanent or if there are plans for reversal, which are the main parts of the question.

==========
archehr_25
==========

[QUESTION]
Why was he equipped with a CPAP machine?

[REFERENCE ANSWER]
The patient was equipped with a CPAP machine in order to maintain his oxygen levels. He was admitted to the hospital for low oxygen levels and shortness of breath due to heart failure. The supplemental oxygen with a positive pressure mask was used in the intensive care unit for his low oxygen levels. The CPAP machine provides positive pressure airflow to the patient to increase oxygen levels while he recovered from his heart failure symptoms.

[EVIDENCE SELECTION RUNS]

    run_id selected_sentence_ids
40       0                   [3]
41       1                   [3]
42       2                   [3]
43       3                   [3]
44       4                   [3]
45       5                   [3]
46       6                   [3]
47       7                   [3]
48       8                   [3]
49       9                   [3]

[REPRESENTATIVE EVIDENCE]
[3] You were temporarily admitted to the intensive care unit, so that you could receive supplemental oxygen through a positive-pressure mask.

[ANSWER RUNS]

    run_id  cluster_label                                                                                                                               answer
40       0              0  He was equipped with a positive-pressure mask to receive supplemental oxygen while temporarily admitted to the intensive care unit.
41       1              0                                                        He was equipped with a positive-pressure mask to receive supplemental oxygen.
42       2              0  He was equipped with a positive-pressure mask to receive supplemental oxygen while temporarily admitted to the intensive care unit.
43       3              0                                                        He was equipped with a positive-pressure mask to receive supplemental oxygen.
44       4              0                                                        He was equipped with a positive-pressure mask to receive supplemental oxygen.
45       5              0                                                        He was equipped with a positive-pressure mask to receive supplemental oxygen.
46       6              0                                                        He was equipped with a positive-pressure mask to receive supplemental oxygen.
47       7              0                                                        He was equipped with a positive-pressure mask to receive supplemental oxygen.
48       8              0                       He was equipped with a positive-pressure mask to receive supplemental oxygen while in the intensive care unit.
49       9              0                                                        He was equipped with a positive-pressure mask to receive supplemental oxygen.

[LLM JUDGE]

   correct                                                                                                                representative_answer                                                                                                                                reason
4    False  He was equipped with a positive-pressure mask to receive supplemental oxygen while temporarily admitted to the intensive care unit.  The generated answer does not mention the CPAP machine or the patient's heart failure, which are key points in the reference answer.

==========
archehr_21
==========

[QUESTION]
Is there more specific information about the alcoholic cirrhosis with advanced Hepatic encephalopathy to predict his lifespan?

[REFERENCE ANSWER]
The patient's lifespan is shortened for many reasons: his progressive liver failure and hepatic encephalopathy are refractory to traditional treatment meaning there will be no improvement. He is not a candidate for liver transplant, and his liver will ultimately fail. Related to liver failure, his kidney function failed and he became anuric. He has no nutrition due to vomiting and removing the NGT. The antibiotics for urinary infection were discontinued when he moved to comfort measures.

[EVIDENCE SELECTION RUNS]

   run_id                selected_sentence_ids
0       0                 [1, 3, 4, 6, 13, 15]
1       1                 [1, 3, 4, 6, 13, 15]
2       2                 [1, 3, 4, 6, 13, 15]
3       3                 [1, 3, 4, 6, 13, 15]
4       4                 [1, 3, 4, 6, 13, 15]
5       5  [1, 3, 4, 6, 9, 11, 13, 15, 16, 19]
6       6                 [1, 3, 4, 6, 13, 15]
7       7                 [1, 3, 4, 6, 13, 15]
8       8      [1, 3, 4, 6, 9, 11, 13, 15, 16]
9       9                 [1, 3, 4, 6, 13, 15]

[REPRESENTATIVE EVIDENCE]
[1] History of Present Illness: 47M with decompensated alcoholic and HCV cirrhosis, with history of hepatic encephalopathy, ascites, esophageal varices s/p banding and Budd-Chiari syndrome treated conservatively without anticoagulation, several recent admissions (last [**Date range (1) 29493**]), who presents now with altered mental status, hyponatremia, and [**Last Name (un) **].
[3] Cirrhosis complicated by hepatic encepthlopathy, varices, portal gastropathy, and ascites is admitted with toxic metabolic encephalopathy and acute renal failure.
[4] # Goals of care: Patient admitted with progressive liver failure and hepatic encephalopathy refractory to traditional treatment.
[6] Given that he was not a candidate for transplant and had exceeded the limits of medical therapy, a family meeting was held with his mother and HCP [**Name (NI) **] and goals of care were transitioned to comfort.
[13] #Alcoholic/HCV Cirrhosis: complicated by hepatic encepthlopathy, varaces, portal gastropathy, and ascites.
[15] Hepatology was consulted and did not think he was a candidate for transplant.

[ANSWER RUNS]

   run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                                                                                      answer
0       0              0                          The patient has decompensated alcoholic and HCV cirrhosis with advanced hepatic encephalopathy, portal gastropathy, ascites, and a history of Budd-Chiari syndrome. He is not a candidate for transplant and has exceeded the limits of medical therapy. Goals of care have transitioned to comfort, indicating progressive liver failure. Recent admissions occurred within the date range 29493.
1       1              0                                       The patient has decompensated alcoholic and HCV cirrhosis with advanced hepatic encephalopathy, ascites, esophageal varices, and Budd-Chiari syndrome. He is not a candidate for transplant and has exceeded the limits of medical therapy. Goals of care have transitioned to comfort, indicating progressive liver failure. Recent admissions occurred within the date range 29493.
2       2              0     The patient has decompensated alcoholic and HCV cirrhosis complicated by hepatic encephalopathy, ascites, esophageal varices, and Budd-Chiari syndrome. He is not a candidate for transplant and has exceeded the limits of medical therapy. Goals of care were transitioned to comfort due to progressive liver failure and refractory hepatic encephalopathy. Recent admissions occurred within the date range 29493.
3       3              0                                             The patient has end-stage alcoholic and HCV cirrhosis complicated by hepatic encephalopathy, ascites, esophageal varices, portal gastropathy, and Budd-Chiari syndrome. He is not a candidate for transplant and has exceeded the limits of medical therapy. Goals of care have transitioned to comfort due to progressive liver failure and refractory hepatic encephalopathy.
4       4              0     The patient has decompensated alcoholic and HCV cirrhosis complicated by hepatic encephalopathy, ascites, esophageal varices, and Budd-Chiari syndrome. He is not a candidate for transplant and has exceeded the limits of medical therapy. Goals of care have transitioned to comfort due to progressive liver failure and refractory hepatic encephalopathy. Recent admissions occurred within the date range 29493.
5       5              0    The patient has end-stage alcoholic and HCV cirrhosis complicated by hepatic encephalopathy, ascites, esophageal varices, and Budd-Chiari syndrome. He is not a candidate for transplant and has exceeded the limits of medical therapy. Goals of care have transitioned to comfort, indicating progressive liver failure and refractory hepatic encephalopathy. Recent admissions occurred within the date range 29493.
6       6              0              The patient has decompensated alcoholic and HCV cirrhosis complicated by hepatic encephalopathy, ascites, esophageal varices, and Budd-Chiari syndrome. He has experienced progressive liver failure and hepatic encephalopathy refractory to traditional treatment and is not a candidate for transplant. Goals of care have transitioned to comfort. Recent admissions occurred within the date range 29493.
7       7              0     The patient has decompensated alcoholic and HCV cirrhosis complicated by hepatic encephalopathy, ascites, esophageal varices, and Budd-Chiari syndrome. He is not a candidate for transplant and has exceeded the limits of medical therapy. Goals of care were transitioned to comfort due to progressive liver failure and refractory hepatic encephalopathy. Recent admissions occurred within the date range 29493.
8       8              0  The patient has decompensated alcoholic and HCV cirrhosis complicated by hepatic encephalopathy, ascites, esophageal varices, and Budd-Chiari syndrome. He is not a candidate for transplant and has exceeded the limits of medical therapy, with goals of care transitioned to comfort due to progressive liver failure and refractory hepatic encephalopathy. Recent admissions occurred within the date range of 29493.
9       9              0                                         The patient has decompensated alcoholic and HCV cirrhosis with advanced hepatic encephalopathy, ascites, esophageal varices, and Budd-Chiari syndrome. He is not a candidate for transplant and has exceeded the limits of medical therapy. Goals of care have transitioned to comfort due to progressive liver failure. Recent admissions occurred within the date range of 29493.

[LLM JUDGE]

   correct                                                                                                                                                                                                                                                                                                                                                                               representative_answer                                                                                                                                                                 reason
0    False  The patient has decompensated alcoholic and HCV cirrhosis with advanced hepatic encephalopathy, portal gastropathy, ascites, and a history of Budd-Chiari syndrome. He is not a candidate for transplant and has exceeded the limits of medical therapy. Goals of care have transitioned to comfort, indicating progressive liver failure. Recent admissions occurred within the date range 29493.  The generated answer does not directly address the question about predicting the patient's lifespan, instead focusing on the patient's condition and care transition.

==========
archehr_43
==========

[QUESTION]
Could her bulding thoracic disc cause chest pain?

[REFERENCE ANSWER]
Patient's past medical history is significant of thoracic and lumbar surgical procedure, degenerative joint disease, scoliosis, fibromyalgia, anxiety depression, and chronic back pain. She was evaluated by the chronic pain service that made adjustments to her pain management regiment. Patient worked with physical and occupational therapists who recommended a short term rehab after hospital discharge. Patient's chest pain could be a result of her chronic pain exacerbated by the recent back surgery.

[EVIDENCE SELECTION RUNS]

     run_id selected_sentence_ids
220       0             [1, 3, 6]
221       1             [1, 3, 6]
222       2             [1, 3, 6]
223       3             [1, 3, 6]
224       4             [1, 3, 6]
225       5             [1, 3, 6]
226       6             [1, 3, 6]
227       7             [1, 3, 6]
228       8         [1, 3, 6, 13]
229       9             [1, 3, 6]

[REPRESENTATIVE EVIDENCE]
[1] Brief Hospital Course: ___ F with fibromyalgia, depression anxiety recently s/p thoracic and lumbar instrumentation by Dr. ___ ___ and ___ re-presenting with uncontrolled back pain since surgery.
[3] In setting of recent proceduralization and chronic back pain ___ DJD, scoliosis on background of fibromyalgia/anxiety.
[6] Longstanding history of fibromyalgia, anxiety depression.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                                      answer
220       0              0  The patient has a history of thoracic and lumbar instrumentation for back pain and underlying degenerative joint disease and scoliosis. She also has longstanding fibromyalgia, anxiety, and depression. The patient is presenting with uncontrolled back pain since surgery. The evidence does not directly address whether a bulging thoracic disc can cause chest pain.
221       1              0                           The patient has a history of thoracic and lumbar instrumentation for back pain, degenerative joint disease, and scoliosis, all in the setting of fibromyalgia, anxiety, and depression. She is presenting with uncontrolled back pain since surgery. The evidence does not directly address whether a bulging thoracic disc can cause chest pain.
222       2              0                    The patient has a history of thoracic and lumbar instrumentation for back pain, degenerative joint disease, and scoliosis. She also has longstanding fibromyalgia, anxiety, and depression. Her presentation involves uncontrolled back pain since surgery. The evidence does not directly address whether a bulging thoracic disc can cause chest pain.
223       3              0                        The patient has a history of thoracic and lumbar instrumentation for back pain, degenerative joint disease, and scoliosis. She also has longstanding fibromyalgia, anxiety, and depression. The patient is presenting with uncontrolled back pain since surgery. The evidence does not address whether a bulging thoracic disc can cause chest pain.
224       4              0               The patient has a history of thoracic and lumbar instrumentation for back pain, degenerative joint disease, and scoliosis. She also has longstanding fibromyalgia, anxiety, and depression. The patient is presenting with uncontrolled back pain since surgery. The evidence does not directly address whether a bulging thoracic disc can cause chest pain.
225       5              0       The patient has a history of thoracic and lumbar instrumentation for back pain and longstanding fibromyalgia, anxiety, and depression. Degenerative joint disease and scoliosis are also present. The patient is presenting with uncontrolled back pain since surgery. The evidence does not directly address whether a bulging thoracic disc could cause chest pain.
226       6              0                                            The patient has a history of thoracic and lumbar instrumentation for back pain and underlying degenerative joint disease, scoliosis, fibromyalgia, anxiety, and depression. She presents with uncontrolled back pain since surgery. The evidence does not directly address whether a bulging thoracic disc can cause chest pain.
227       7              0               The patient has a history of thoracic and lumbar instrumentation for back pain, degenerative joint disease, and scoliosis. She also has longstanding fibromyalgia, anxiety, and depression. The patient is presenting with uncontrolled back pain since surgery. The evidence does not directly address whether a bulging thoracic disc can cause chest pain.
228       8              0                                              The patient has a history of fibromyalgia, anxiety, and depression, and recently underwent thoracic and lumbar instrumentation for back pain. She presents with uncontrolled back pain and degenerative joint disease, scoliosis. The evidence does not directly address whether a bulging thoracic disc can cause chest pain.
229       9              0                                              The patient has a history of fibromyalgia, anxiety, and depression, and recently underwent thoracic and lumbar instrumentation for back pain. She presents with uncontrolled back pain and degenerative joint disease, scoliosis. The evidence does not directly address whether a bulging thoracic disc can cause chest pain.

[LLM JUDGE]

    correct                                                                                                                                                                                                                                                                                                                                                       representative_answer                                                                                                                            reason
22    False  The patient has a history of thoracic and lumbar instrumentation for back pain and underlying degenerative joint disease and scoliosis. She also has longstanding fibromyalgia, anxiety, and depression. The patient is presenting with uncontrolled back pain since surgery. The evidence does not directly address whether a bulging thoracic disc can cause chest pain.  The generated answer does not directly address whether a bulging thoracic disc can cause chest pain, which is the main question.

==========
archehr_52
==========

[QUESTION]
What should he do for persistent lightheadedness?

[REFERENCE ANSWER]
Patient might have had encephalitis, but no specific cause was found at the time of discharge. Based on the discharge instructions, there are still some tests pending. If his lightheadedness is intermittent, he should just follow up with the neurology clinic as scheduled. However, if the lightheadedness is persistent and/or if he develops a fever, he should call the neurology clinic to help determine if he should present to the ER.

[EVIDENCE SELECTION RUNS]

     run_id selected_sentence_ids
310       0                [3, 5]
311       1                [3, 5]
312       2                [3, 5]
313       3             [3, 4, 5]
314       4             [3, 4, 5]
315       5                [3, 5]
316       6                [3, 5]
317       7                [3, 5]
318       8             [3, 4, 5]
319       9             [3, 4, 5]

[REPRESENTATIVE EVIDENCE]
[3] We did not find a specific cause at the time of discharge.
[5] If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                answer
310       0              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
311       1              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
312       2              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
313       3              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
314       4              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
315       5              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
316       6              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
317       7              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
318       8              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.
319       9              0  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.

[LLM JUDGE]

    correct                                                                                                                                                 representative_answer                                                    reason
31    False  We did not find a specific cause at the time of discharge. If you have any new symptoms or high fever, please call the neurology clinic or go to the emergency room.  omitted specific guidance for persistent lightheadedness

==========
archehr_42
==========

[QUESTION]
Was it antibiotics or foods that caused cholecystitis?

[REFERENCE ANSWER]
A CT scan of Pt's abdomen and pelvis revealed a 4mm gallstone within the cystic duct resulting in acute cholecystitis. Patient was sent for a laparoscopic cholecystectomy and found to have a gangrenous gallbladder with significant inflammation. Given this finding, she was treated with antibiotics. Patient's status improved post procedure and she was able to advance her diet which would indicate that the cholecystitis was caused by the gallstone. Pain management: prn oxycodone.

[EVIDENCE SELECTION RUNS]

     run_id selected_sentence_ids
210       0                    []
211       1                    []
212       2                    []
213       3                    []
214       4                    []
215       5                    []
216       6                    []
217       7                    []
218       8                    []
219       9                    []

[REPRESENTATIVE EVIDENCE]

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                   answer
210       0              0                                                                              The provided evidence does not address whether antibiotics or food caused cholecystitis. It notes the patient's gallbladder was swollen and she felt better with intravenous antibiotics, but her symptoms returned 12 hours later, leading her to suspect the antibiotics.
211       1              2  The provided evidence does not address whether antibiotics or foods caused the gallbladder swelling (cholecystitis). It notes the patient experienced stomach pain after starting antibiotics for strep throat, was found to have a swollen gallbladder via ultrasound, and temporarily improved with intravenous antibiotics before the pain returned.
212       2              0                                                                                                              The provided evidence does not contain information to determine whether the antibiotics or food caused cholecystitis. The patient’s gallbladder was swollen, and she felt better on intravenous antibiotics but her symptoms have returned.
213       3              0                                                        The provided evidence does not address whether the patient's cholecystitis was caused by antibiotics or food. It notes the patient experienced abdominal pain, gallbladder swelling detected by ultrasound, and improvement with intravenous antibiotics, followed by a return of abdominal pain.
214       4              1                                                                                                                                                                                                                           The provided evidence does not offer information to determine whether the antibiotics or food intake caused the cholecystitis.
215       5              0                                                                                                                The provided evidence does not contain information to determine whether the antibiotics or food caused the gallbladder swelling (cholecystitis). The patient's symptoms improved with intravenous antibiotics, but subsequently worsened.
216       6              0                                                                                                    The provided information does not address whether antibiotics or food intake caused cholecystitis. The patient's gallbladder was noted to be swollen, and she experienced abdominal pain that improved with intravenous antibiotics before returning.
217       7              0                                                                             The provided evidence does not contain information to determine whether the antibiotics or food intake caused the gallbladder swelling (cholecystitis). The patient experienced improvement with intravenous antibiotics but subsequently reported recurring abdominal pain.
218       8              0                                                                                                                        The provided evidence does not address whether antibiotics or foods caused cholecystitis. It notes the patient's gallbladder was swollen and that she felt better with intravenous antibiotics but her stomach pain has returned.
219       9              0                                                                                                                       The provided evidence does not contain information to determine whether the antibiotics or food caused the gallbladder swelling (cholecystitis). The patient's symptoms improved with intravenous antibiotics, but later returned.

[LLM JUDGE]

    correct                                                                                                                                                                                                                                                        representative_answer                                                                                                                                                                                             reason
21    False  The provided evidence does not address whether antibiotics or food caused cholecystitis. It notes the patient's gallbladder was swollen and she felt better with intravenous antibiotics, but her symptoms returned 12 hours later, leading her to suspect the antibiotics.  The generated answer introduces new, unsupported information and contradicts the expert reference answer, which states that the cholecystitis was caused by a gallstone, not antibiotics or food.

==========
archehr_28
==========

[QUESTION]
How is the patient expected to control the pain after being treated for pancreatitis?

[REFERENCE ANSWER]
The patient can control her pain post treatment for pancreatitis with Vicodin. Her discharge medication instructions indicate she can take Vicodin every six hours as needed for pain. She initially was on morphine and Vicodin twice a day. The morphine was stopped and the Vicodin frequency was increased to better control her pain. There are no other medications listed for pain management. The patient's abdominal pain was resolved.

[EVIDENCE SELECTION RUNS]

    run_id selected_sentence_ids
70       0               [4, 13]
71       1               [4, 13]
72       2               [4, 13]
73       3               [4, 13]
74       4               [4, 13]
75       5               [4, 13]
76       6               [4, 13]
77       7               [4, 13]
78       8               [4, 13]
79       9               [4, 13]

[REPRESENTATIVE EVIDENCE]
[4] The patient's abdominal pain gradually resolved, initially as NPO with IVF/TPN and then advanced a regular diet.
[13] ADDED: - STARTED Daptomycin 350 mg iv every 24 hours until [**2109-6-11**] for 14 day course - STARTED Pantoprazole 40 mg by mouth daily - Remeron (mirtazapine) 7.5 mg by mouth at night CHANGED: - INCREASED frequency of vicodin from twice a day to every 6 hours as needed for pain REMOVED: - STOPPED

[ANSWER RUNS]

    run_id  cluster_label                                                                                                                                                                                                                                                                                                                                  answer
70       0              1                  The patient's abdominal pain gradually resolved initially with NPO, IVF/TPN, and then advancement to a regular diet. Pain management included increasing the frequency of vicodin to every 6 hours as needed. Additionally, pantoprazole and Remeron were started, and a 14-day course of Daptomycin was administered.
71       1              0                  The patient's abdominal pain gradually resolved initially with NPO, intravenous fluids, and total parenteral nutrition, followed by advancement to a regular diet. Pain management included increasing the frequency of vicodin to every 6 hours as needed. Additionally, pantoprazole and mirtazapine were initiated.
72       2              0  The patient's abdominal pain gradually resolved with a period of NPO and intravenous fluids/total parenteral nutrition, followed by advancement to a regular diet. Pain management included increasing the frequency of vicodin to every 6 hours as needed. Other medications administered were Daptomycin, Pantoprazole, and Remeron.
73       3              0                                                        The patient's abdominal pain gradually resolved initially with NPO, intravenous fluids, and total parenteral nutrition, then with advancement to a regular diet. Vicodin was increased to every 6 hours as needed for pain. Additionally, Pantoprazole and Remeron were started.
74       4              0                                                            The patient's abdominal pain gradually resolved with a period of NPO with intravenous fluids/total parenteral nutrition, followed by advancement to a regular diet. Vicodin was increased to every 6 hours as needed for pain. Pantoprazole and Remeron were also initiated.
75       5              0          The patient's abdominal pain gradually resolved initially with NPO, intravenous fluids (IVF), and total parenteral nutrition (TPN), followed by advancement to a regular diet. Pain management included increasing the frequency of vicodin to every 6 hours as needed. Additionally, pantoprazole and Remeron were initiated.
76       6              0                                              The patient's abdominal pain gradually resolved initially with NPO, intravenous fluids, and total parenteral nutrition, followed by advancement to a regular diet. Vicodin was increased to every 6 hours as needed for pain control. Additionally, pantoprazole and Remeron were started.
77       7              0                     The patient's abdominal pain gradually resolved initially with NPO, intravenous fluids, and total parenteral nutrition, followed by advancement to a regular diet. Vicodin was increased to every 6 hours as needed for pain control. Other medications administered include Daptomycin, Pantoprazole, and Remeron.
78       8              0                                         The patient's abdominal pain gradually resolved initially with NPO, intravenous fluids (IVF), and total parenteral nutrition (TPN), followed by advancement to a regular diet. Vicodin was increased to every 6 hours as needed for pain control. Pantoprazole and Remeron were also initiated.
79       9              0                                                                             The patient's abdominal pain gradually resolved initially with NPO, intravenous fluids, and total parenteral nutrition, followed by advancement to a regular diet. Pain management included increasing the frequency of vicodin to every 6 hours as needed.

[LLM JUDGE]

   correct                                                                                                                                                                                                                                                                                                   representative_answer                                                                                                                reason
7    False  The patient's abdominal pain gradually resolved initially with NPO, intravenous fluids, and total parenteral nutrition, followed by advancement to a regular diet. Pain management included increasing the frequency of vicodin to every 6 hours as needed. Additionally, pantoprazole and mirtazapine were initiated.  inclusion of unsupported claims (pantoprazole and mirtazapine) and omission of initial pain management with morphine

==========
archehr_93
==========

[QUESTION]
Can her breathlessness on exertion be related to the treatment she received for heart failure?

[REFERENCE ANSWER]
Patient had a dangerously low heart rate related to her diltiazem medication and pneumonia. Diltiazem was discontinued and pneumonia was treated with fluids and antibiotics. Patient's condition improved with this treatment. Patient had tachycardia due to deconditioning from pneumonia and withdrawal from diltiazem. Patient's breathlessness on exertion could be related to the ongoing significant troubles with heart rate, for which she has been referred to a cardiologist as an outpatient for medication adjustments.

[EVIDENCE SELECTION RUNS]

     run_id selected_sentence_ids
720       0          [3, 4, 6, 9]
721       1          [3, 4, 6, 9]
722       2          [3, 4, 6, 9]
723       3          [3, 4, 6, 9]
724       4          [3, 4, 6, 9]
725       5          [3, 4, 6, 9]
726       6          [3, 4, 6, 9]
727       7          [3, 4, 6, 9]
728       8          [3, 4, 6, 9]
729       9          [3, 4, 6, 9]

[REPRESENTATIVE EVIDENCE]
[3] You were admitted to [**Hospital1 18**] for evaluation and treatment of nausea and vomiting and were found to have a dangerously low heart rate from your diltiazem as well as pneumonia.
[4] Your diltiazem medication was held, you were monitored in the intensive care unit, given fluids and antibiotics and your condition improved.
[6] You had a fast heart rate (not dangerously fast) which was likely due to pneumonia, deconditioning (being sick in the hospital), and withdrawal from the diltiazem which is gradually improving.
[9] Given your significant troubles with your heart rate we are referring you to see a cardiologist as an outpatient to make some medication adjustments.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                             answer
720       0              0                            The evidence does not indicate heart failure or damage to the heart. You were admitted for nausea, vomiting, and a dangerously low heart rate related to diltiazem and pneumonia. Your heart rate was also likely influenced by deconditioning and diltiazem withdrawal. A cardiologist referral is planned for medication adjustments.
721       1              2                                            The records indicate you were admitted for nausea, vomiting, and a dangerously low heart rate, and pneumonia. Your heart rate was likely due to pneumonia, deconditioning, and withdrawal from diltiazem. You are being referred to a cardiologist for medication adjustments given concerns regarding your heart rate.
722       2              0  The evidence does not indicate heart failure was diagnosed. You were admitted for nausea, vomiting, and a dangerously low heart rate likely due to diltiazem and pneumonia. Your fast heart rate was likely due to pneumonia, deconditioning, and diltiazem withdrawal. A cardiologist referral is planned for medication adjustments related to your heart rate.
723       3              0                        The evidence does not indicate heart failure or damage to the heart. You were admitted for nausea, vomiting, and a dangerously low heart rate related to diltiazem and pneumonia. Your heart rate was likely elevated due to pneumonia, deconditioning, and diltiazem withdrawal. A cardiologist referral is planned to adjust medications.
724       4              0                                    The evidence does not indicate a diagnosis of heart failure. You were admitted for nausea, vomiting, and a dangerously low heart rate related to diltiazem and pneumonia. Your fast heart rate was likely due to pneumonia, deconditioning, and diltiazem withdrawal. A cardiologist referral is planned to adjust medications.
725       5              3                                      Your heart rate issues, likely due to pneumonia, deconditioning, and diltiazem withdrawal, prompted a cardiology referral for medication adjustments. The evidence does not indicate a diagnosis of heart failure or a direct link between your treatment for nausea, vomiting, and pneumonia and breathlessness on exertion.
726       6              4                                                                                         Your current breathlessness on exertion may be related to a fast heart rate, which was likely due to pneumonia, deconditioning, and withdrawal from diltiazem. A cardiologist referral is recommended to make medication adjustments and further evaluate your heart rate.
727       7              1                                           Your records indicate you were treated for a dangerously low heart rate and pneumonia, requiring intensive care. A fast heart rate was likely due to pneumonia, deconditioning, and withdrawal from diltiazem. You are being referred to a cardiologist for medication adjustments related to these heart rate concerns.
728       8              2                                                       Your records indicate you were admitted for nausea, vomiting, and a dangerously low heart rate, and pneumonia. A fast heart rate was likely due to pneumonia, deconditioning, and withdrawal from diltiazem. You are being referred to a cardiologist for medication adjustments related to your heart rate.
729       9              0              The evidence does not indicate heart failure was diagnosed. You were admitted for nausea, vomiting, and a dangerously low heart rate, likely due to diltiazem and pneumonia. A fast heart rate was also observed, potentially related to pneumonia, deconditioning, and diltiazem withdrawal. A cardiologist referral was made to adjust medications.

[LLM JUDGE]

    correct                                                                                                                                                                                                                                                                                                                    representative_answer                                                                                                                             reason
72    False  The evidence does not indicate heart failure or damage to the heart. You were admitted for nausea, vomiting, and a dangerously low heart rate related to diltiazem and pneumonia. Your heart rate was also likely influenced by deconditioning and diltiazem withdrawal. A cardiologist referral is planned for medication adjustments.  The generated answer does not address the question about breathlessness on exertion being related to treatment for heart failure.

==========
archehr_34
==========

[QUESTION]
What did they find in the psych evaluation and what may have caused this episode?

[REFERENCE ANSWER]
Pt in hospital for confusion and seizure due to low magnesium, potassium, and calcium levels. Psych did not see the patient, neurology, social work, PT and OT did. What may have caused this episode is low electrolytes, chronic diarrhea, alcohol use, and poor nutrition. CT scan was negative. Neuro recommended correction of electrolytes and to abstain from alcohol. Pt being discharged to a rehab facility to help regain strength and ensure safe return back home.

[EVIDENCE SELECTION RUNS]

     run_id     selected_sentence_ids
130       0  [1, 2, 3, 4, 5, 6, 8, 9]
131       1     [1, 2, 3, 4, 5, 8, 9]
132       2     [1, 2, 3, 4, 5, 8, 9]
133       3     [1, 2, 3, 4, 5, 8, 9]
134       4     [1, 2, 3, 4, 5, 8, 9]
135       5     [1, 2, 3, 4, 5, 8, 9]
136       6     [1, 2, 3, 4, 5, 8, 9]
137       7     [1, 2, 3, 4, 5, 8, 9]
138       8     [1, 2, 3, 4, 5, 8, 9]
139       9     [1, 2, 3, 4, 5, 8, 9]

[REPRESENTATIVE EVIDENCE]
[1] Discharge Instructions: You were admitted to the hospital with confusion, low magnesium, potassium, and calcium.
[2] In the ED, you had a seizure that was most likely due to your low electrolytes and also alcohol withdrawal.
[3] Your low electrolytes were attributed to your chronic diarrhea, alcohol use, and poor nutrition.
[4] A CT scan of your head did not show any acute problems.
[5] Our neurology colleagues saw you and recommended correction of your electrolytes and abstinence from alcohol.
[8] The following changes were made in your medications: START Magnesium Oxide 400 mg twice daily with breakfast and dinner START Amlodipine 5 mg by mouth daily START Folic Acid 1 mg daily START Thiamine 100 mg daily START Vitamin D 50,000 units weekly (on Saturdays) for 6 weeks
[9] DISCONTINUE Magnesium Chloride

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                                                  answer
130       0              0                              The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possibly alcohol withdrawal, attributed to chronic diarrhea, alcohol use, and poor nutrition. Neurology colleagues recommended correcting electrolytes and abstinence from alcohol.
131       1              0                                         The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possibly alcohol withdrawal, attributed to chronic diarrhea, alcohol use, and poor nutrition. Neurology recommended correcting electrolytes and abstaining from alcohol.
132       2              0                                         The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possibly alcohol withdrawal, attributed to chronic diarrhea, alcohol use, and poor nutrition. Neurology recommended correcting electrolytes and abstinence from alcohol.
133       3              0                         The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possibly alcohol withdrawal. Contributing factors included chronic diarrhea, alcohol use, and poor nutrition. Neurology recommended correcting electrolytes and abstinence from alcohol.
134       4              0  The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possibly alcohol withdrawal. Electrolyte imbalances were attributed to chronic diarrhea, alcohol use, and poor nutrition. Neurology colleagues recommended correcting electrolytes and abstaining from alcohol.
135       5              0                                          The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possibly alcohol withdrawal, attributed to chronic diarrhea, alcohol use, and poor nutrition. Neurology recommended electrolyte correction and abstinence from alcohol.
136       6              0            The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possible alcohol withdrawal. Neurology colleagues recommended correcting electrolytes and abstaining from alcohol. Medications were adjusted to include magnesium oxide and folic acid, among others.
137       7              0                              The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possibly alcohol withdrawal, attributed to chronic diarrhea, alcohol use, and poor nutrition. Neurology colleagues recommended correcting electrolytes and abstaining from alcohol.
138       8              0                              The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possibly alcohol withdrawal, attributed to chronic diarrhea, alcohol use, and poor nutrition. Neurology colleagues recommended correcting electrolytes and abstinence from alcohol.
139       9              0                                         The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possibly alcohol withdrawal, attributed to chronic diarrhea, alcohol use, and poor nutrition. Neurology recommended correcting electrolytes and abstaining from alcohol.

[LLM JUDGE]

    correct                                                                                                                                                                                                                                                                                                                                       representative_answer                                                                                                                                                                                                     reason
13     True  The patient was admitted with confusion, low magnesium, potassium, and calcium. A CT scan showed no acute problems. The episode was likely due to low electrolytes and possibly alcohol withdrawal, attributed to chronic diarrhea, alcohol use, and poor nutrition. Neurology colleagues recommended correcting electrolytes and abstinence from alcohol.  The generated answer accurately covers the key points of the patient's condition, the likely causes of the episode, and the recommended treatment, matching the substance of the expert reference answer.

==========
archehr_74
==========

[QUESTION]
What is her expected course of recovery after craniotomy?

[REFERENCE ANSWER]
Pt transferred to a rehab post craniotomy. Pt directed to take medications as ordered. Medications include steroids, which she should take with meals or a glass of milk to protect her stomach. Per recommendations, activity is important to prevent complications. Feeling tired and fatigued first few weeks after the discharge is normal. Pt instructed to increase activity slowly even if feeling good. Call the surgeon if her cough is productive with yellow or green sputum.

[EVIDENCE SELECTION RUNS]

     run_id                                                                                    selected_sentence_ids
530       0  [2, 21, 22, 23, 24, 26, 27, 28, 32, 44, 45, 46, 48, 50, 51, 54, 56, 58, 60, 62, 63, 65, 67, 69, 71, 73]
531       1      [2, 21, 22, 23, 24, 26, 27, 28, 32, 44, 45, 46, 48, 50, 51, 54, 56, 60, 62, 63, 65, 67, 69, 71, 73]
532       2                                                      [2, 21, 22, 23, 24, 26, 27, 28, 32, 44, 45, 46, 60]
533       3      [2, 21, 22, 23, 24, 26, 27, 28, 32, 44, 45, 46, 48, 50, 51, 54, 56, 60, 62, 63, 65, 67, 69, 71, 73]
534       4                                                          [2, 21, 22, 23, 24, 26, 27, 28, 32, 44, 45, 46]
535       5       [2, 7, 21, 22, 23, 24, 26, 27, 28, 32, 44, 45, 46, 48, 50, 51, 54, 56, 60, 62, 63, 65, 69, 71, 73]
536       6                                                          [2, 21, 22, 23, 24, 26, 27, 28, 32, 44, 45, 46]
537       7                                                          [2, 21, 22, 23, 24, 26, 27, 28, 32, 44, 45, 46]
538       8                                                      [2, 21, 22, 23, 24, 26, 27, 28, 32, 44, 45, 46, 60]
539       9                                                          [2, 21, 22, 23, 24, 26, 27, 28, 32, 44, 45, 46]

[REPRESENTATIVE EVIDENCE]
[2] She was screened for rehab on [**4-9**], and was transferred via ambulance to [**Hospital **] Rehab on [**2166-4-11**].
[21] The first few weeks after you are discharged you may feel tired or fatigued.
[22] This is normal.
[23] You should become a little stronger every day.
[24] Activity is the most important measure you can take to prevent complications and to begin to feel like yourself again.
[26] Follow the activity instructions given to you by your doctor and therapist.
[27] ??????
[28] Increase your activity slowly; do not do too much because you are feeling good.
[32] If you feel light headed or fatigued after increasing activity, rest, decrease the amount of activity that you do, and begin building your tolerance to activity more slowly.
[44] With any surgery there are risks of complications.
[45] Although your surgery is over, there is the possibility of some of these complications developing.
[46] These complications include: infection, blood clots, or neurological changes.
[60] Severe headache or change in headache.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                                                                                                                                                                                                answer
530       0              0                                   Following craniotomy, fatigue is normal in the first few weeks after discharge. You should become a little stronger each day, and activity is important to prevent complications and improve well-being. Increase activity slowly, and rest if you feel light headed or fatigued. There are risks of complications, including infection, blood clots, or neurological changes, and severe headache or change in headache can occur.
531       1              0                                       Following craniotomy, fatigue is normal in the first few weeks after discharge. You should gradually become stronger each day, and activity is important to prevent complications and improve recovery. Increase activity slowly, and rest if you feel lightheaded or fatigued. Be aware of potential complications like infection, blood clots, or neurological changes, and report any severe headache or change in headache.
532       2              0                                      Following craniotomy, fatigue is normal in the first few weeks after discharge. You should gradually become stronger each day, and activity is important to prevent complications and improve recovery. Increase activity slowly, and rest if you feel lightheaded or fatigued. There are risks of complications such as infection, blood clots, or neurological changes, and a severe headache or change in headache may occur.
533       3              0                            Following craniotomy, fatigue is normal in the first few weeks after discharge. You should gradually become stronger each day, and activity is important to prevent complications and improve well-being. Increase activity slowly, and rest if you feel light headed or fatigued. There is a possibility of complications such as infection, blood clots, or neurological changes. Severe headache or change in headache should be noted.
534       4              0                                                    Following craniotomy, fatigue is normal in the first few weeks after discharge. You should gradually become stronger each day and increase activity to prevent complications. Follow your doctor and therapist's instructions, and increase activity slowly. Be aware that complications like infection, blood clots, or neurological changes are possible, and a severe headache or change in headache can occur.
535       5              0  Following craniotomy, fatigue is normal in the first few weeks after discharge. You should gradually become stronger each day and increase activity to prevent complications. Follow your doctor's and therapist’s instructions, and increase activity slowly to avoid lightheadedness or fatigue. There is a possibility of complications such as infection, blood clots, or neurological changes, and a severe headache or change in headache should be monitored.
536       6              0                                                Following craniotomy, fatigue is normal in the first few weeks after discharge. You should become stronger daily, and activity is important to prevent complications and improve well-being. Increase activity slowly, and rest if you feel light headed or fatigued. There are risks of complications such as infection, blood clots, or neurological changes, and a severe headache or change in headache can occur.
537       7              0                                                         Following craniotomy, fatigue is normal in the first few weeks after discharge. You should gradually become stronger each day, and activity is important to prevent complications. Increase activity slowly, and rest if you feel lightheaded or fatigued. Be aware of potential complications such as infection, blood clots, or neurological changes, and report any severe headache or change in headache.
538       8              0                                                 Following craniotomy, fatigue is normal in the first few weeks after discharge. You should become stronger daily, and activity is important to prevent complications and improve recovery. Increase activity slowly, and rest if you feel lightheaded or fatigued. Be aware of potential complications such as infection, blood clots, or neurological changes, and report any severe headache or change in headache.
539       9              0                                                           Following craniotomy, fatigue is normal in the first few weeks after discharge. You should become stronger daily and activity is important to prevent complications. Increase activity slowly, and rest if you feel light headed or fatigued. There is a possibility of complications such as infection, blood clots, or neurological changes, and a severe headache or change in headache should be noted.

[LLM JUDGE]

    correct                                                                                                                                                                                                                                                                                                                                                                                                                representative_answer                                                                                                                                                                              reason
53     True  Following craniotomy, fatigue is normal in the first few weeks after discharge. You should become a little stronger each day, and activity is important to prevent complications and improve well-being. Increase activity slowly, and rest if you feel light headed or fatigued. There are risks of complications, including infection, blood clots, or neurological changes, and severe headache or change in headache can occur.  The generated answer covers key aspects of recovery after craniotomy, including normal fatigue, importance of activity, gradual increase in activity, and potential complications.

==========
archehr_24
==========

[QUESTION]
Why was the patient intubated?

[REFERENCE ANSWER]
This patient was hypoxic with low saturation levels on a non rebreather mask. The oxygenation level dropped with minimal exertion. In the ED, the patient was found to have worsening hypoxemia and an increased respiratory rate. This was concerning for increased work of breathing and required the patient to be intubated. Intubation helps the patient receive the oxygen he needs for his organs and tissues.

[EVIDENCE SELECTION RUNS]

    run_id selected_sentence_ids
30       0                   [4]
31       1             [4, 2, 3]
32       2                   [4]
33       3                   [4]
34       4             [4, 2, 3]
35       5                   [4]
36       6                   [4]
37       7                   [4]
38       8                   [4]
39       9                   [4]

[REPRESENTATIVE EVIDENCE]
[4] He was noted to be significantly hypoxic and tachypnic and was intubated due to concern for increasing work of breathing.

[ANSWER RUNS]

    run_id  cluster_label                                                                                                              answer
30       0              0  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.
31       1              0  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.
32       2              0  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.
33       3              0  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.
34       4              0  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.
35       5              0  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.
36       6              0  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.
37       7              0  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.
38       8              0  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.
39       9              0  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.

[LLM JUDGE]

   correct                                                                                               representative_answer                                           reason
3     True  The patient was intubated due to significant hypoxia and tachypnea, with concern for increasing work of breathing.  accurately summarizes the reason for intubation

==========
archehr_26
==========

[QUESTION]
Why was he given antibiotics during his hospital stay?

[REFERENCE ANSWER]
While the patient was in the hospital intubated for agitation and sedation, he developed pneumonia. Pneumonia is a lung infection, and antibiotics are needed to treat the infection and improve the patient's lung function. The patient required a seven day course of antibiotics for this infection. Because he received antibiotics, his pneumonia improved. Without antibiotics, the patient's lung status would not have improved and may have caused further complications while he was intubated.

[EVIDENCE SELECTION RUNS]

    run_id selected_sentence_ids
50       0                [3, 4]
51       1                [3, 4]
52       2                [3, 4]
53       3                [3, 4]
54       4                [3, 4]
55       5                [3, 4]
56       6                [3, 4]
57       7                [3, 4]
58       8                [3, 4]
59       9                [3, 4]

[REPRESENTATIVE EVIDENCE]
[3] Your intubation was complicated by a pneumonia and you were transferred to [**Hospital1 18**] for further management of your pneumonia and your mental status changes.
[4] You were treated with a 7 day course of antibiotics for your pneumonia and you improved.

[ANSWER RUNS]

    run_id  cluster_label                                                                                                                                                                                                                answer
50       0              2                                        Antibiotics were administered to treat pneumonia, which complicated your intubation. You received a 7-day course of antibiotics and demonstrated improvement during that time.
51       1              0          Your father was treated with a 7-day course of antibiotics for pneumonia. He was transferred to [Hospital1 18] for management of pneumonia and mental status changes. He improved with antibiotic treatment.
52       2              0            Your father was treated with a 7-day course of antibiotics for pneumonia. He was transferred to Hospital1 18 for management of pneumonia and mental status changes. He improved with antibiotic treatment.
53       3              0  Your father was treated with a 7-day course of antibiotics for pneumonia. He was transferred to [Hospital1 18] for management of his pneumonia and mental status changes, and he improved with antibiotic treatment.
54       4              0          Your father was treated with a 7-day course of antibiotics for pneumonia. He was transferred to [Hospital1 18] for management of pneumonia and mental status changes. He improved with antibiotic treatment.
55       5              0      Your father was treated with a 7-day course of antibiotics for pneumonia. He was transferred to [Hospital1 18] for management of pneumonia and mental status changes, and he improved with antibiotic treatment.
56       6              0        Your father was treated with a 7-day course of antibiotics for pneumonia. He was transferred to Hospital1 18 for management of pneumonia and mental status changes, and he improved with antibiotic treatment.
57       7              0        Your father was treated with a 7-day course of antibiotics for pneumonia. He was transferred to Hospital1 18 for management of his pneumonia and mental status changes. He improved with antibiotic treatment.
58       8              1                                                Antibiotics were administered to treat your father’s pneumonia, which complicated his intubation. He received a 7-day course of antibiotics and subsequently improved.
59       9              0            Your father was treated with a 7-day course of antibiotics for pneumonia. He was transferred to Hospital1 18 for management of pneumonia and mental status changes. He improved with antibiotic treatment.

[LLM JUDGE]

   correct                                                                                                                                                                                         representative_answer                                                                                                               reason
5     True  Your father was treated with a 7-day course of antibiotics for pneumonia. He was transferred to [Hospital1 18] for management of pneumonia and mental status changes. He improved with antibiotic treatment.  The generated answer accurately states the patient was given antibiotics for pneumonia and improved with treatment.

==========
archehr_95
==========

[QUESTION]
What was the reason for her blackouts? What was her hemoglobin level?

[REFERENCE ANSWER]
Patient was admitted after an episode of fainting. Multiple tests were run and they were able to rule out a heart attack, no signs of a serious arrhythmia, the echo showed improvement from previous testing, and her CT scans were normal. It was determined that a vagal reaction to nausea/vomiting is what caused the patient to faint. Patient was also found to have anemia which indicates her hemoglobin levels fall below the normal range.

[EVIDENCE SELECTION RUNS]

     run_id selected_sentence_ids
740       0             [3, 4, 7]
741       1             [3, 4, 7]
742       2             [3, 4, 7]
743       3             [3, 4, 7]
744       4             [3, 4, 7]
745       5             [3, 4, 7]
746       6             [3, 4, 7]
747       7             [3, 4, 7]
748       8             [3, 4, 7]
749       9             [3, 4, 7]

[REPRESENTATIVE EVIDENCE]
[3] You were admitted after fainting which we think was a "vagal" reaction to your nausea/vomiting.
[4] You did not have a heart attack, you did not have a serious arrhythmia when we interrogated your pacemaker, your ecchocardiogram was improved from last month, CT of your abdomen, head and neck were normal.
[7] You also have low iron levels causing anemia.

[ANSWER RUNS]

     run_id  cluster_label                                                                                                                                                                                                                                                                                answer
740       0              0                     The fainting episodes were likely a "vagal" reaction to nausea and vomiting. Cardiac evaluation, including interrogation of your pacemaker and echocardiogram, did not reveal a heart attack or serious arrhythmia. You also have low iron levels causing anemia.
741       1              0                     The fainting episodes were likely a “vagal” reaction to nausea and vomiting. Cardiac evaluation, including interrogation of your pacemaker and echocardiogram, did not reveal a heart attack or serious arrhythmia. You also have low iron levels causing anemia.
742       2              0                                             The fainting episodes were likely a "vagal" reaction to nausea and vomiting. Cardiac evaluation revealed no heart attack or serious arrhythmia, and imaging studies were normal. You also have low iron levels, which are causing anemia.
743       3              0                     The fainting episodes were likely a "vagal" reaction to nausea and vomiting. Cardiac evaluation, including interrogation of your pacemaker and echocardiogram, did not reveal a heart attack or serious arrhythmia. You also have low iron levels causing anemia.
744       4              0               The fainting episodes were likely a "vagal" reaction to nausea and vomiting. Cardiac evaluation, including interrogation of your pacemaker and echocardiogram, did not reveal a heart attack or serious arrhythmia. You have low iron levels, which are causing anemia.
745       5              1                 Your blackouts were likely due to a "vagal" reaction to nausea and vomiting. Investigations, including electrocardiogram and CT scans, ruled out a heart attack, arrhythmia, or other serious abnormalities. You also have low iron levels, which are causing anemia.
746       6              0         Your fainting episodes were likely a "vagal" reaction to nausea and vomiting. Cardiac evaluation, including interrogation of your pacemaker and echocardiogram, did not reveal a heart attack or serious arrhythmia. You also have low iron levels, which are causing anemia.
747       7              1                                               Your blackouts were likely a "vagal" reaction to nausea and vomiting. Cardiac evaluation revealed no heart attack, arrhythmia, or abnormalities on echocardiogram or CT scans. You also have low iron levels, which are causing anemia.
748       8              0            Your fainting episodes were likely "vagal" reactions related to nausea and vomiting. Cardiac evaluation, including interrogation of your pacemaker and echocardiogram, did not reveal a heart attack or arrhythmia. Additionally, you have low iron levels causing anemia.
749       9              0  The fainting episodes were likely a "vagal" reaction to nausea and vomiting. Cardiac evaluation, including interrogation of your pacemaker and echocardiogram, did not reveal a heart attack or serious arrhythmia. You also have low iron levels, which are contributing to anemia.

[LLM JUDGE]

    correct                                                                                                                                                                                                                                              representative_answer                                                                                                                                                                                         reason
74     True  The fainting episodes were likely a "vagal" reaction to nausea and vomiting. Cardiac evaluation, including interrogation of your pacemaker and echocardiogram, did not reveal a heart attack or serious arrhythmia. You also have low iron levels causing anemia.  The generated answer correctly identifies the cause of the blackouts as a vagal reaction to nausea and vomiting, and also mentions the patient's anemia, which implies low hemoglobin levels.

==========
archehr_23
==========

[QUESTION]
Why was she given antibiotics during her hospital stay?

[REFERENCE ANSWER]
The patient was given antibiotics during her hospital stay because of a lung infection. The patient was noted to have low levels of oxygen and a chest x-ray was ordered. it indicated the patient was developing pneumonia. IV antibiotics were initiated to treat the pneumonia. The patient showed improvement right away after starting the antibiotics. Therefore, the antibiotics were necessary during her hospital stay.

[EVIDENCE SELECTION RUNS]

    run_id selected_sentence_ids
20       0                [5, 6]
21       1                [5, 6]
22       2                [5, 6]
23       3                [5, 6]
24       4                [5, 6]
25       5                [5, 6]
26       6                [5, 6]
27       7                [5, 6]
28       8                [5, 6]
29       9                [5, 6]

[REPRESENTATIVE EVIDENCE]
[5] On [**2174-2-11**], it was noted that you were not holding your oxygen levels as high as we would like so a chest x-ray was done, and indicated that you were developing a pneumonia.
[6] We started IV antibiotics for this right away, and you improved.

[ANSWER RUNS]

    run_id  cluster_label                                                                                                                                                                                                                                                                         answer
20       0              0                                                                              Antibiotics were initiated on [2174-2-11] because a chest x-ray indicated the development of pneumonia. The patient’s condition improved following the administration of intravenous antibiotics.
21       1              0                                                                                     Antibiotics were initiated intravenously because a chest x-ray on February 11, 2024, indicated the patient was developing pneumonia. The patient improved after receiving the antibiotics.
22       2              0                                                                                    Antibiotics were initiated on 2174-2-11 due to a developing pneumonia indicated by a chest x-ray. The patient's condition improved following the administration of intravenous antibiotics.
23       3              0                                                                        Antibiotics were initiated intravenously because a chest x-ray on February 11, 2024, indicated the patient was developing pneumonia. The patient subsequently improved after receiving the antibiotics.
24       4              1                          Antibiotics were initiated on 2174-2-11 because a chest x-ray indicated the patient was developing pneumonia. Oxygen levels were not being maintained as desired prior to this finding. The patient improved after receiving intravenous antibiotics.
25       5              0                                                                                            Antibiotics were initiated intravenously because a chest x-ray on [2174-2-11] indicated the patient was developing pneumonia. The patient improved after receiving the antibiotics.
26       6              0                                                                              Antibiotics were initiated on [2174-2-11] because a chest x-ray indicated the development of pneumonia. The patient’s condition improved following the administration of intravenous antibiotics.
27       7              1  Antibiotics were initiated on February 11, 2174, because a chest x-ray indicated the development of pneumonia. Your oxygen levels were not being maintained as desired prior to treatment. You subsequently improved following the administration of intravenous antibiotics.
28       8              0                                                                              Antibiotics were initiated on [2174-2-11] because a chest x-ray indicated the development of pneumonia. The patient’s condition improved following the administration of intravenous antibiotics.
29       9              0                                                                            Antibiotics were initiated intravenously because a chest x-ray on [2174-2-11] indicated the development of pneumonia. The patient demonstrated improvement following the initiation of antibiotics.

[LLM JUDGE]

   correct                                                                                                                                                                              representative_answer                                                                                                             reason
2     True  Antibiotics were initiated on [2174-2-11] because a chest x-ray indicated the development of pneumonia. The patient’s condition improved following the administration of intravenous antibiotics.  The generated answer accurately states the reason for antibiotics and the improvement in the patient's condition.

In [ ]:
# Check evidence changes in Unstable-Stable cases

for case_id in [
    "archehr_21",
    "archehr_43",
    "archehr_34",
    "archehr_74",
]:

    case = case_lookup[case_id]

    case_evidence = evidence_runs[
        evidence_runs["case_id"] == case_id
    ]

    print("\n", "=="*5)
    print(case_id)
    print("=="*5)

    all_ids = [
        str(x)
        for ids in case_evidence["selected_sentence_ids"]
        for x in ids
    ]

    counts = pd.Series(all_ids).value_counts()

    for sentence in case["sentences"]:

        sentence_id = str(
            sentence["sentence_id"]
        )

        if sentence_id in counts.index:
            print(
                f'[{sentence["sentence_id"]}] '
                f'{counts[sentence_id]}/10 - '
                f'{sentence["text"]}'
            )

In [ ]:
# Check evidence changes in Stable-Variable cases

for case_id in [
    "archehr_42",
    "archehr_28",
    "archehr_26",
    "archehr_95",
]:

    case = case_lookup[case_id]

    case_evidence = evidence_runs[
        evidence_runs["case_id"] == case_id
    ]

    print("\n", "=="*5)
    print(case_id)
    print("=="*5)

    all_ids = [
        str(x)
        for ids in case_evidence["selected_sentence_ids"]
        for x in ids
    ]

    counts = pd.Series(all_ids).value_counts()

    for sentence in case["sentences"]:

        sentence_id = str(
            sentence["sentence_id"]
        )

        if sentence_id in counts.index:
            print(
                f'[{sentence["sentence_id"]}] '
                f'{counts[sentence_id]}/10 - '
                f'{sentence["text"]}'
            )

In [ ]:
# Check evidence changes in Unstable-Variable cases

for case_id in [
    "archehr_51",
    "archehr_54",
    "archehr_82",
    "archehr_101",
]:

    case = case_lookup[case_id]

    case_evidence = evidence_runs[
        evidence_runs["case_id"] == case_id
    ]

    print("\n", "=="*5)
    print(case_id)
    print("=="*5)

    all_ids = [
        str(x)
        for ids in case_evidence["selected_sentence_ids"]
        for x in ids
    ]

    counts = pd.Series(all_ids).value_counts()

    for sentence in case["sentences"]:

        sentence_id = str(
            sentence["sentence_id"]
        )

        if sentence_id in counts.index:
            print(
                f'[{sentence["sentence_id"]}] '
                f'{counts[sentence_id]}/10 - '
                f'{sentence["text"]}'
            )